import { lazy, Suspense, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowRight, BarChart3, Building2, Car, ChevronDown, ChevronLeft, ChevronRight, CloudRain, Compass, Crosshair, Download, Layers, MapPin, Menu, Moon, Pause, Play, Search, SlidersHorizontal, Snowflake, Sparkles, Sun, Users, X } from 'lucide-react';
import type { StaticDemoProvider } from './data/StaticDemoProvider';
import { loadDemoProvider } from './data/loadDemoProvider';
import type { DemoContextV1, DemoSnapshot, PublicFictionalPersonV1 } from './types';
import { decodeLocation, DEFAULT_CONTEXT, encodeLocation, LEGACY_DATASET_ID, ROUTES, type DemoRoute } from './navigation';
import { ResidentChat } from './ResidentChat';
import { FictionalPortrait } from './FictionalPortrait';
import { cohortSnapshot, cohortDescription, hasCohort } from './analytics/analyticsModel';
import { ObservedSummary } from './analytics/ObservedSummary';
const DemoCity=lazy(()=>import('./DemoCity').then(m=>({default:m.DemoCity})));
const DemoAnalytics=lazy(()=>import('./analytics').then(m=>({default:m.DemoAnalytics})));
const DemoScenarios=lazy(()=>import('./analytics').then(m=>({default:m.DemoScenarios})));
const number=new Intl.NumberFormat('ru-RU');
const EMPLOYMENT={child:'Ребёнок',student:'Учится',employed:'Работает',retired:'На пенсии',not_employed:'Не работает'};
type Selection={kind:'person'|'vehicle'|'building';id:string;label?:string;coordinates?:[number,number]};
const parseSelection=(s:string|null):Selection|null=>{if(!s)return null;const [kind,...id]=s.split(':');return ['person','vehicle','building'].includes(kind)&&id.length?{kind:kind as Selection['kind'],id:id.join(':')}:null};

/** A changed request is loading immediately; neither old results nor fabricated zeroes leak into a new slice. */
function useAsyncValue<T>(request:(signal:AbortSignal)=>Promise<T>) {
 const [result,setResult]=useState<{request:typeof request;value?:T;error?:string}|null>(null);
 useEffect(()=>{
  const abort=new AbortController();
  Promise.resolve().then(()=>request(abort.signal)).then(value=>{if(!abort.signal.aborted)setResult({request,value})}).catch(error=>{if(!abort.signal.aborted)setResult({request,error:error instanceof Error?error.message:String(error)})});
  return()=>abort.abort();
 },[request]);
 const current=result?.request===request?result:null;
 return {ready:current!==null&&'value' in current,value:current?.value,error:current?.error};
}

function MiniPyramid({snapshot}:{snapshot:DemoSnapshot}){const max=Math.max(1,...snapshot.ageSex.flatMap(r=>[r.male,r.female]));return <svg viewBox="0 0 272 130" className="mini-pyramid" role="img" aria-label="Возрастно-половая структура демонабора"><text x="90" y="12" textAnchor="end">Мужчины</text><text x="181" y="12">Женщины</text>{[...snapshot.ageSex].reverse().map((r,i)=><g key={r.ageBand}><rect x={119-r.male/max*91} y={24+i*20} width={r.male/max*91} height="12" fill="#33b8c8"/><rect x="151" y={24+i*20} width={r.female/max*91} height="12" fill="#aa96ce"/><text x="135" y={34+i*20} textAnchor="middle">{r.ageBand}</text></g>)}</svg>}
function Summary({provider,context,navigate,onContextChange}:{provider:StaticDemoProvider;context:DemoContextV1;navigate:(r:DemoRoute)=>void;onContextChange:(c:Partial<DemoContextV1>)=>void}){
 const source=provider.getSnapshot(context.scenario,context.year,context.territoryId);const territory=provider.territories.find(t=>t.id===context.territoryId);
 const filtered=hasCohort(context.cohort);const snapshot=useMemo(()=>source?cohortSnapshot(provider,source,context.cohort):null,[provider,source,context.cohort?.ageBand,context.cohort?.sex,context.cohort?.employment]);
 const previousSource=provider.getSnapshot(context.scenario,context.year-1,context.territoryId);
 const previous=useMemo(()=>previousSource?cohortSnapshot(provider,previousSource,context.cohort):null,[provider,previousSource,context.cohort?.ageBand,context.cohort?.sex,context.cohort?.employment]);
 if(context.analyticsSource!=='fictional'){
   if(!provider.observedCity||context.territoryId!=='RU-CHE-SET')return <section className="summary"><h2>Нет наблюдений этой территории</h2><p className="muted">Проверенная статистика доступна для Челябинского городского округа целиком. Она не распределяется между демонстрационными районами.</p><button className="primary" onClick={()=>onContextChange({territoryId:'RU-CHE-SET',cohort:null})}>Весь городской округ</button><button onClick={()=>onContextChange({analyticsSource:'fictional'})}>Персонажи демонабора</button></section>;
   return <ObservedSummary reference={provider.observedCity} year={context.observedYear??2024} onAnalytics={()=>navigate('analytics')} onScenarios={()=>navigate('scenarios')} characterCount={provider.getSnapshot(context.scenario,context.year,'RU-CHE-SET')?.population??0}/>;
 }
 if(!snapshot)return <section className="summary"><h2>Нет данных выбранного среза</h2><p>Выберите доступную территорию и год.</p></section>;
 const isLegacy=provider.manifest.datasetId===LEGACY_DATASET_ID&&!filtered&&context.year===2026&&context.territoryId==='RU-CHE-SET';const previousValue=previous?.population??(isLegacy?8225:null);const delta=previousValue===null?null:snapshot.population-previousValue;
 return <section className="summary" data-testid="territory-summary"><div className="panel-heading"><h2>Сводка территории</h2><ChevronDown size={17}/></div><p className="muted">{territory?.name||'Челябинск'} · демонабор</p>
 <div className="population-row"><strong data-testid="population-value">{number.format(snapshot.population)}</strong>{delta!==null&&<span className={delta<0?'negative':'positive'}>{delta>0?'+':''}{number.format(delta)}<small>к {context.year-1} году</small></span>}</div><p className="metric-label">{filtered?'Жителей в выбранной группе':'Жителей в демонаборе'}</p>{filtered&&<p className="caption">{cohortDescription(context.cohort)}</p>}<p className="disclosure">Не численность реального города</p>
 <div className="summary-section"><h3>Изменение численности</h3>{previousValue!==null?<><div className="trend-labels"><span>{context.year-1} · {number.format(previousValue)}</span><span>{context.year} · {number.format(snapshot.population)}</span></div><svg viewBox="0 0 280 57" className="mini-trend" aria-label="Изменение между двумя срезами"><path d={delta===0?'M8 28 L272 28':delta!==null&&delta<0?'M8 13 L272 43':'M8 43 L272 13'} fill="none" stroke="#08c5d7" strokeWidth="2"/><circle cx="8" cy={delta===0?28:delta!==null&&delta<0?13:43} r="4" fill="#08c5d7"/><circle cx="272" cy={delta===0?28:delta!==null&&delta<0?43:13} r="5" fill="#08c5d7"/></svg></>:<p className="caption">Предыдущий срез недоступен</p>}</div>
 <div className="summary-section"><h3>Структура населения</h3><MiniPyramid snapshot={snapshot}/></div>
 <div className="summary-actions"><button className="primary" onClick={()=>navigate('analytics')}><BarChart3 size={17}/>Открыть аналитику<ArrowRight size={16}/></button><button onClick={()=>navigate('scenarios')}><SlidersHorizontal size={17}/>Сравнить сценарии</button></div>
 <p className="source-note">{isLegacy?'Начальные итоги: synthetic-chelyabinsk-v1':'Иллюстративный сценарный набор'}<br/>Демонстрация интерфейса, не научный прогноз<br/><a href={`${import.meta.env.BASE_URL}assets/living-city/ATTRIBUTION.html`} target="_blank" rel="noopener noreferrer">Источники и лицензии</a></p></section>;
}
function PersonDetails({person,provider,context,onMap}:{person:PublicFictionalPersonV1;provider:StaticDemoProvider;context:DemoContextV1;onMap:()=>void}){
 const presence=provider.getPresence(person.id,context.presentationMinutes,context.scenario,context.year);
 return <><div className="person-hero"><FictionalPortrait person={person}/><div><p className="caption">Вымышленный житель</p><h2>{person.name}</h2><p>{person.age} лет · {person.occupation}</p></div></div><div className="presence"><MapPin size={17}/><span>{presence?.activity||'Учтён в демонаборе'}</span></div><dl className="profile-fields"><div><dt>Территория</dt><dd>{person.territoryName}</dd></div><div><dt>Занятость</dt><dd>{EMPLOYMENT[person.employment]}</dd></div><div><dt>Домохозяйство</dt><dd>{person.householdSize === null ? '—' : `${person.householdSize} чел.`}</dd></div><div><dt>Срез</dt><dd>01.01.{context.year}</dd></div></dl><p className="biography">{person.biography}</p><div className="interest-tags">{person.interests.map(x=><span key={x}>{x}</span>)}</div><button className="map-person-button" onClick={onMap}><Crosshair size={17}/>Показать на карте</button><ResidentChat person={person} context={context} presence={presence}/></>;
}
function Inspector({selection,provider,context,onClose,onSelect,onMap}:{selection:Selection;provider:StaticDemoProvider;context:DemoContextV1;onClose:()=>void;onSelect:(s:Selection)=>void;onMap:(p:PublicFictionalPersonV1)=>void}){
 const [offset,setOffset]=useState(0);useEffect(()=>setOffset(0),[selection.id,context.scenario,context.year]);
 const presenceMinute=selection.kind==='person'?0:Math.floor(context.presentationMinutes);
 const prepare=useCallback(async (signal:AbortSignal)=>{
  if(selection.kind==='person')await provider.preparePerson(selection.id,context.scenario,context.year,signal);
  else if(selection.kind==='building')await provider.prepareBuilding(selection.id,presenceMinute,context.scenario,context.year,signal);
  else await provider.prepareVehicle(selection.id,presenceMinute,context.scenario,context.year,signal);
  return true;
 },[provider,selection.kind,selection.id,context.scenario,context.year,presenceMinute]);
 const prepared=useAsyncValue(prepare);
 const person=prepared.ready&&selection.kind==='person'?provider.getPerson(selection.id,context.scenario,context.year):null;
 const occupancy=prepared.ready&&selection.kind==='building'?provider.getBuildingOccupancy(selection.id,context.presentationMinutes,context.scenario,context.year,offset,50):null;
 const vehicle=prepared.ready&&selection.kind==='vehicle'?provider.getVehicle(selection.id,context.presentationMinutes,context.scenario,context.year):null;
 return <section className="inspector" data-testid="selection-inspector"><div className="inspector-top"><span>{selection.kind==='person'?'Профиль жителя':selection.kind==='building'?'Жизнь здания':'Пассажиры автомобиля'}</span><button className="icon-button" onClick={onClose} aria-label="Закрыть профиль"><X size={19}/></button></div>
 {prepared.error?<p role="alert">Не удалось загрузить сведения: {prepared.error}</p>:!prepared.ready?<p role="status">Загружаем {selection.kind==='person'?'профиль жителя':selection.kind==='building'?'жителей здания':'пассажиров автомобиля'}…</p>:person?<PersonDetails person={person} provider={provider} context={context} onMap={()=>onMap(person)}/>:occupancy?<><div className="object-heading"><Building2 size={30}/><h2>{selection.label||'Здание'}</h2></div><p className="caption">Назначение жителей зданию: визуальный синтез</p><div className="occupancy-stat"><strong>{occupancy.presentNow}</strong><span>сейчас внутри</span></div><dl className="profile-fields"><div><dt>Назначено жителей</dt><dd>{occupancy.assignedResidents}</dd></div><div><dt>Работников</dt><dd>{occupancy.assignedWorkers}</dd></div></dl><h3>Находятся внутри</h3>{occupancy.items.map(p=><button className="roster-row" key={p.id} onClick={()=>onSelect({kind:'person',id:p.id})}><span>{p.name}<small>{p.age} лет · {p.occupation}</small></span><ChevronRight size={16}/></button>)}{!occupancy.items.length&&<p className="muted">В выбранный момент здесь нет назначенных демонстрационных жителей.</p>}<div className="pagination"><button disabled={offset===0} onClick={()=>setOffset(x=>Math.max(0,x-50))}>Назад</button><span>{occupancy.items.length?offset+1:0}–{offset+occupancy.items.length}</span><button disabled={occupancy.nextOffset===null} onClick={()=>setOffset(occupancy.nextOffset!)}>Далее</button></div></>:vehicle?<><div className="object-heading"><Car size={30}/><h2>{vehicle.label}</h2></div><p className="caption">Автомобиль и маршрут — визуальный синтез</p><div className="occupancy-stat"><strong>{vehicle.occupancy}/{vehicle.capacity}</strong><span>мест занято</span></div><h3>Пассажиры</h3>{vehicle.occupants.map(p=><button className="roster-row" key={p.id} onClick={()=>onSelect({kind:'person',id:p.id})}><span>{p.name}<small>{p.occupation}</small></span><ChevronRight size={16}/></button>)}</>:<p className="muted">Объект отсутствует в выбранном срезе или уже завершил поездку. Выберите другого жителя или вернитесь к сводке.</p>}</section>;
}
function Agents({provider,context,onContextChange,onSelect}:{provider:StaticDemoProvider;context:DemoContextV1;onContextChange:(c:Partial<DemoContextV1>)=>void;onSelect:(s:Selection)=>void}){
 const query=context.agentQuery??'';const offset=context.agentOffset??0;const setQuery=(value:string)=>onContextChange({agentQuery:value,agentOffset:0});const setOffset=(change:(n:number)=>number)=>onContextChange({agentOffset:change(offset)});
 const indexedSearch=provider.manifest.datasetId==='omnitwin-fictional-city-v2';

 const request=useCallback((signal:AbortSignal)=>provider.queryPeople({scenario:context.scenario,year:context.year,territoryId:context.territoryId,ageBand:context.cohort?.ageBand,sex:context.cohort?.sex,employment:context.cohort?.employment,query,offset,limit:50},signal),[provider,context.scenario,context.year,context.territoryId,context.cohort?.ageBand,context.cohort?.sex,context.cohort?.employment,query,offset]);
 const result=useAsyncValue(request);const page=result.value;
 return <section className="agents-view" data-testid="agents-view" aria-busy={!result.ready&&!result.error}><div className="page-heading"><div><p className="caption">От агрегатов к отдельному жителю</p><h1>Население в деталях</h1>{page&&<p className="muted">{number.format(page.total)} вымышленных жителей в выбранном срезе. Каждый профиль связан с аналитикой.</p>}</div></div>
 <div className="agent-filters"><label className="search-field"><Search size={18}/><input aria-label={indexedSearch?'ID жителя':'Поиск жителя'} aria-describedby={indexedSearch?'city-id-search-help':undefined} placeholder={indexedSearch?'ID жителя':'Имя, занятие или ID'} value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Пол<select aria-label="Пол жителя" value={context.cohort?.sex||''} onChange={e=>onContextChange({cohort:{...context.cohort,sex:e.target.value as 'male'|'female'||undefined}})}><option value="">Все</option><option value="male">Мужчины</option><option value="female">Женщины</option></select></label><label>Возраст<select aria-label="Возрастная группа" value={context.cohort?.ageBand||''} onChange={e=>onContextChange({cohort:{...context.cohort,ageBand:(e.target.value||undefined) as NonNullable<DemoContextV1['cohort']>['ageBand']}})}><option value="">Все группы</option>{['0-17','18-34','35-54','55-69','70+'].map(x=><option key={x}>{x}</option>)}</select></label>{context.cohort&&<button onClick={()=>onContextChange({cohort:null})}>Сбросить группу</button>}</div>
 {indexedSearch&&<p id="city-id-search-help" className="caption">Поиск по ID; имя и занятие — в карточке</p>}
 {result.error?<p role="alert">Не удалось загрузить жителей: {result.error}</p>:!page?<p role="status">Загружаем жителей выбранного среза…</p>:<><div className="table-scroll"><table><thead><tr><th>Житель</th><th>Возраст</th><th>Занятие</th><th>Территория</th><th>Домохозяйство</th><th/></tr></thead><tbody>{page.items.map(p=><tr key={p.id}><td><button className="person-link" onClick={()=>onSelect({kind:'person',id:p.id})}>{p.name}</button><small className="table-id">{p.id}</small></td><td>{p.age}</td><td>{p.occupation}</td><td>{p.territoryName}</td><td>{p.householdSize === null ? '—' : `${p.householdSize} чел.`}</td><td><button aria-label={`Открыть профиль ${p.name}`} className="icon-button" onClick={()=>onSelect({kind:'person',id:p.id})}><ChevronRight size={18}/></button></td></tr>)}</tbody></table></div>{!page.items.length&&<p className="muted">В выбранном срезе жители не найдены.</p>}<div className="pagination"><button onClick={()=>setOffset(x=>Math.max(0,x-50))} disabled={offset===0}><ChevronLeft size={16}/>Предыдущие</button><span>{page.items.length?page.offset+1:0}–{page.items.length?page.offset+page.items.length:0} из {number.format(page.total)}</span><button disabled={page.nextOffset===null} onClick={()=>onContextChange({agentOffset:page.nextOffset!})}>Следующие<ChevronRight size={16}/></button></div></>}</section>;
}
function About({provider}:{provider:StaticDemoProvider}){return <article className="about-view"><p className="caption">Исследовательская платформа</p><h1>OmniTwin: от населения страны<br/>к повседневной жизни человека</h1><p className="about-lead">Агентная модель помогает исследовать демографические изменения. Карта, аналитика и сценарии — разные способы изучать одно состояние населения.</p><div className="about-columns"><section><h2>Что работает в демонстрации</h2><ul><li>Потоковая 3D-карта Челябинска и визуальный синтез городской жизни.</li><li>Связанные профили, агрегаты, возрастно-половая структура и CSV-экспорт.</li><li>Сравнение подготовленных иллюстративных сценариев.</li><li>Разговор с вымышленным жителем: серверный ИИ при подключённом сервисе, подписанные демореплики без него.</li></ul></section><section><h2>Что ещё предстоит исследовать</h2><ul><li>Завершить национальный расчёт и независимую научную валидацию.</li><li>Оценить неопределённость и прогнозную способность на отложенных данных.</li><li>Подключить проверенные национальные результаты к этим интерфейсам.</li></ul></section></div><section className="about-disclosure"><h2>Честная граница демонстрации</h2><p>На первом экране и в режиме «Статистика города» показаны опубликованные агрегаты Росстата / Челябинскстата с датами и источниками. Это наблюдаемые оценки, не результаты нашей модели. Все интерактивные жители вымышлены; их отдельный набор из {number.format(provider.manifest.initialPopulation)} персонажей в начальном срезе не является переписью или репрезентативной выборкой города. Сценарии 2026–2036 годов относятся только к этому демонстрационному набору и не являются прогнозом Челябинска. Научная модель ещё не проходит все критерии; эта версия не предназначена для официального прогноза.</p><p>География: OpenStreetMap / OpenFreeMap. Внешний вид, размещение жителей и движение — визуальный синтез. Логотип РУДН использован для представления заявки на конкурс, не как утверждение об одобрении проекта университетом.</p></section><p>Автор: <a href="https://sitkovskiy.ru/" target="_blank" rel="noreferrer">Ситковский А.М.</a> · <a href="https://github.com/Arseniy24RUS/OmniTwin-demo" target="_blank" rel="noreferrer">Исходный код демо</a></p></article>}

function ContextBar({provider,context,observed,onChange,onAbout}:{provider:StaticDemoProvider|null;context:DemoContextV1;observed:boolean;onChange:(patch:Partial<DemoContextV1>)=>void;onAbout:()=>void}) {
 return <div className={`context-bar ${observed?'context-bar--observed':''}`}>
  <label className="territory-select"><MapPin size={16}/><select aria-label="Территория" value={context.territoryId} onChange={e=>onChange({territoryId:e.target.value,cohort:null})}>{(provider?.territories||[{id:'RU-CHE-SET',name:'Челябинск'}]).map(t=><option key={t.id} value={t.id}>{t.id==='RU-CHE-SET'?'Челябинский городской округ':`${t.name} · демо`}</option>)}</select></label>
  <label className="statistics-source"><select aria-label="Источник статистики" value={context.analyticsSource??'observed'} onChange={e=>onChange({analyticsSource:e.target.value as 'observed'|'fictional'})}><option value="observed">Статистика города</option><option value="fictional">Демонабор персонажей</option></select></label>
  {observed?<label>На дату<select aria-label="Год наблюдений" value={context.observedYear??2024} onChange={e=>onChange({observedYear:Number(e.target.value)})}>{(provider?.observedCity?.snapshots.map(s=>s.year)||[2024]).map(y=><option key={y} value={y}>01.01.{y}</option>)}</select></label>:<><label>Демосрез<select aria-label="Демографический срез" value={context.year} onChange={e=>onChange({year:Number(e.target.value)})}>{Array.from({length:11},(_,i)=>2026+i).map(y=><option key={y} value={y}>01.01.{y}</option>)}</select></label><label className="scenario-select"><select aria-label="Активный сценарий" value={context.scenario} onChange={e=>onChange({scenario:e.target.value as DemoContextV1['scenario']})}>{(provider?.scenarios||[{id:'baseline',label:'Базовый демосценарий'}]).map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label></>}
  <button className="demo-disclosure" onClick={onAbout}><span/>{observed?'Челябинскстат · персонажи вымышлены':'Демонстрационные данные'}</button>
 </div>;
}

export default function App(){
 const initial=useRef(decodeLocation(window.location.hash));const [route,setRoute]=useState(initial.current.route);const [context,setContext]=useState(initial.current.context);const [selection,setSelection]=useState<Selection|null>(parseSelection(initial.current.selection));
 const navigationRevisionRef=useRef(0);const [navigationRevision,setNavigationRevision]=useState(0);const knownHash=useRef(window.location.hash);
 const [loadedProvider,setProvider]=useState<StaticDemoProvider|null>(null);const providerRef=useRef<StaticDemoProvider|null>(null);const [error,setError]=useState('');const [menu,setMenu]=useState(false);const [expanded,setExpanded]=useState(false);const [tour,setTour]=useState<number|null>(null);
 const detailPanelRef=useRef<HTMLElement>(null);
 const collapsePanel=useCallback(()=>{setExpanded(false);if(detailPanelRef.current)detailPanelRef.current.scrollTop=0},[]);
 const provider=loadedProvider&&(!context.datasetId||loadedProvider.manifest.datasetId===context.datasetId)?loadedProvider:null;
 const referenceView=(route==='world'||route==='analytics')&&context.analyticsSource!=='fictional';
 useEffect(()=>{
  const requested=context.datasetId;const abort=new AbortController();setError('');
  if(providerRef.current?.manifest.datasetId===requested){setProvider(providerRef.current);return()=>abort.abort();}
  setProvider(null);
  loadDemoProvider(import.meta.env.BASE_URL,requested||undefined,abort.signal).then(p=>{
   if(abort.signal.aborted)return;
   providerRef.current=p;setProvider(p);
   setContext(c=>c.datasetId===requested?{...c,datasetId:p.manifest.datasetId,territoryId:p.territories.some(t=>t.id===c.territoryId)?c.territoryId:'RU-CHE-SET'}:c);
  }).catch(e=>{if(!abort.signal.aborted)setError(e instanceof Error?e.message:String(e))});
  return()=>abort.abort();
 },[context.datasetId]);
 useEffect(()=>{const restore=()=>{
  if(location.hash===knownHash.current)return;
  knownHash.current=location.hash;const state=decodeLocation(location.hash);
  // History restore is a new map command; callbacks from the preceding instance are stale.
  navigationRevisionRef.current+=1;setNavigationRevision(navigationRevisionRef.current);
  setRoute(state.route);setContext(state.context);setSelection(parseSelection(state.selection));
 };addEventListener('popstate',restore);addEventListener('hashchange',restore);return()=>{removeEventListener('popstate',restore);removeEventListener('hashchange',restore)}},[]);
 useEffect(()=>{const hash=encodeLocation(route,context,selection?`${selection.kind}:${selection.id}`:null);history.replaceState(null,'',hash);knownHash.current=hash;document.title=`OmniTwin · ${ROUTES[route]}`},[route,context,selection]);
 const update=useCallback((patch:Partial<DemoContextV1>)=>setContext(c=>({...c,...patch,...(['scenario','year','territoryId','cohort'].some(key=>key in patch)?{agentOffset:0}:{})})),[]);
 const updateCamera=useCallback((camera:DemoContextV1['camera'])=>{if(navigationRevisionRef.current===navigationRevision)update({camera})},[navigationRevision,update]);
 const navigate=useCallback((next:DemoRoute)=>{history.pushState(null,'',encodeLocation(next,context));setRoute(next);setSelection(null);setMenu(false);setExpanded(false)},[context]);
 useEffect(()=>{if(route!=='world'||!context.playing)return;let last=performance.now();const timer=setInterval(()=>{const now=performance.now();const dt=Math.min(2,(now-last)/1000);last=now;if(document.visibilityState==='visible')setContext(c=>({...c,presentationMinutes:(c.presentationMinutes+dt*c.speed/60)%1440}))},1000);return()=>clearInterval(timer)},[route,context.playing,context.speed]);
 const select=useCallback((s:Selection|null)=>{setSelection(s);setExpanded(Boolean(s))},[]);
 const onMap=useCallback((p:PublicFictionalPersonV1)=>{const presence=provider?.getPresence(p.id,context.presentationMinutes,context.scenario,context.year);const pos=presence?.position;history.pushState(null,'',encodeLocation('world',context,`person:${p.id}`));setRoute('world');setSelection({kind:'person',id:p.id});collapsePanel();if(pos)update({camera:{...context.camera,longitude:pos[0],latitude:pos[1],zoom:17.4,pitch:55}})},[provider,context,update,collapsePanel]);
 const tourSteps=[{route:'world',title:'Город как представление данных',text:'Сводка справа описывает выбранный срез. Люди на улице — лишь видимая часть демонабора.'},{route:'analytics',title:'Изучите структуру населения',text:'Пирамида, компоненты прироста и таблица связаны одним набором данных. Выберите возрастную группу.'},{route:'scenarios',title:'Сравните возможные траектории',text:'Подготовленные сценарии показывают различия в численности и возрастной структуре. Это иллюстрация, не прогноз.'},{route:'agents',title:'За агрегатами — отдельные жители',text:'Откройте профиль. Его характеристики соответствуют выбранному сценарию и демографическому срезу.'},{route:'world',title:'Разговор и повседневная жизнь',text:'Нажмите на человека, автомобиль или здание. Карточки связаны с одним состоянием присутствия.'},{route:'world',title:'От демонстрации к исследованию',text:'Вечер меняет освещение и движение, но не демографические показатели. Научные результаты подключаются после валидации.'}];
 const stepTour=(i:number)=>{if(i>=tourSteps.length){setTour(null);return;}setTour(i);navigate(tourSteps[i].route as DemoRoute);if(i===5)update({presentationMinutes:1230});};
 if(error)return <main className="loading-screen"><h1>Демонабор не загружен</h1><p>Карта и показатели не подменяются выдуманным ответом при ошибке загрузки.</p><code>{error}</code><button onClick={()=>location.reload()}>Повторить</button></main>;
 return <div className="demo-app"><header className="app-header"><a href="#/world" onClick={e=>{e.preventDefault();navigate('world')}} className="brand" aria-label="OmniTwin — живой мир"><img src={`${import.meta.env.BASE_URL}rudn-white.png`} alt="РУДН"/><span>OmniTwin<small>Челябинск</small></span></a><nav className={menu?'open':''} aria-label="Основная навигация">{Object.entries(ROUTES).map(([key,label])=><a key={key} href={encodeLocation(key as DemoRoute,context)} aria-current={route===key?'page':undefined} onClick={e=>{e.preventDefault();navigate(key as DemoRoute)}}>{label}</a>)}</nav><a className="author" href="https://sitkovskiy.ru/" target="_blank" rel="noreferrer">Автор: <span>Ситковский А.М.</span></a><button className="menu-toggle icon-button" aria-label="Открыть меню" onClick={()=>setMenu(m=>!m)}><Menu size={23}/></button></header>
 <ContextBar provider={provider} context={context} observed={referenceView} onChange={patch=>{update(patch);setSelection(null)}} onAbout={()=>navigate('about')}/>
 {!provider?<main className="loading-screen"><div className="loading-orbit"/><h2>Подготавливаем Челябинск</h2><p>Проверяем целостность демонстрационного набора…</p></main>:<main className={`app-main route-${route}`}>
 {route==='world'?<><div className="city-stage" data-testid="city-stage"><Suspense fallback={<div className="map-loading">Загружаем 3D-карту…</div>}><DemoCity key={`${provider.manifest.datasetId}:${navigationRevision}`} provider={provider} context={context} selectedId={selection?.id||null} onCameraChange={updateCamera} onSelect={s=>select(s as Selection|null)}/></Suspense><button className="tour-button" onClick={()=>stepTour(0)}><Play size={17}/>Начать экскурсию</button><div className="map-tools"><button aria-label="Центр Челябинска" onClick={()=>update({camera:{...DEFAULT_CONTEXT.camera}})}><Crosshair size={21}/></button><button aria-label="Переключить 2D и 3D" onClick={()=>update({camera:{...context.camera,pitch:context.camera.pitch?0:55}})}><Layers size={20}/><small>{context.camera.pitch?'3D':'2D'}</small></button><button aria-label="Открыть список жителей" onClick={()=>navigate('agents')}><Users size={21}/></button></div><div className="presentation-clock"><button className="play-button" data-testid="play-toggle" aria-label={context.playing?'Приостановить движение':'Запустить движение'} onClick={()=>update({playing:!context.playing})}>{context.playing?<Pause size={20}/>:<Play size={20}/>}</button><div className="clock-label"><strong>{String(Math.floor(context.presentationMinutes/60)).padStart(2,'0')}:{String(Math.floor(context.presentationMinutes%60)).padStart(2,'0')}</strong><span>Время визуализации</span></div><input type="range" aria-label="Время визуализации" min="0" max="1439" value={context.presentationMinutes} onChange={e=>update({presentationMinutes:Number(e.target.value)})}/><select aria-label="Скорость движения" value={context.speed} onChange={e=>update({speed:Number(e.target.value)})}>{[1,4,16].map(x=><option key={x} value={x}>{x}×</option>)}</select><label className="weather-control">{context.weather==='rain'?<CloudRain size={22}/>:context.weather==='snow'?<Snowflake size={22}/>:context.presentationMinutes>=1200||context.presentationMinutes<360?<Moon size={22}/>:<Sun size={22}/>}<select aria-label="Погода" value={context.weather} onChange={e=>update({weather:e.target.value as DemoContextV1['weather']})}><option value="clear">Ясно</option><option value="cloudy">Облачно</option><option value="rain">Дождь</option><option value="snow">Снег</option></select></label></div></div><aside ref={detailPanelRef} className={`detail-panel ${expanded?'expanded':''}`}><button className="sheet-handle" aria-label="Развернуть или свернуть сводку" onClick={()=>{if(expanded)collapsePanel();else setExpanded(true)}}><span/></button>{selection?<Inspector selection={selection} provider={provider} context={context} onClose={()=>select(null)} onSelect={select} onMap={onMap}/>:<Summary provider={provider} context={context} navigate={navigate} onContextChange={update}/>}</aside></>:
 <><div className="page-content"><Suspense fallback={<div className="loading-screen">Загружаем представление…</div>}>{route==='analytics'?<DemoAnalytics provider={provider} context={context} onContextChange={update} onSelectCohort={cohort=>{update({cohort});navigate('agents')}}/>:route==='scenarios'?<DemoScenarios provider={provider} context={context} onContextChange={update}/>:route==='agents'?<Agents provider={provider} context={context} onContextChange={update} onSelect={select}/>:<About provider={provider}/>}</Suspense></div>{selection&&<aside ref={detailPanelRef} className="detail-panel inspector-overlay"><Inspector selection={selection} provider={provider} context={context} onClose={()=>select(null)} onSelect={select} onMap={onMap}/></aside>}</>}
 </main>}
 {tour!==null&&<section className="tour-panel" role="dialog" aria-label="Экскурсия"><div><span className="caption">{tour+1} / {tourSteps.length}</span><button aria-label="Закрыть экскурсию" className="icon-button" onClick={()=>setTour(null)}><X size={18}/></button></div><h2>{tourSteps[tour].title}</h2><p>{tourSteps[tour].text}</p><button className="primary" onClick={()=>stepTour(tour+1)}>{tour===tourSteps.length-1?'Завершить':'Далее'}<ArrowRight size={17}/></button></section>}
 </div>;
}
