// Generated by `python -m omnitwin_api.codegen`; DO NOT EDIT.
// Normative sources: packages/contracts/schemas/*.schema.json

export const GENERATED_SCHEMA_SHA256 = {
  "agent-catalog-response-v1.schema.json": "af45eab34ad8c674fd8f9cded2e1ad7a255587b01126c73177fb8c4900828868",
  "agent-mobility-presentation-v1.schema.json": "277698ab26c3191b9f7fd86fd2cad98c007270dbcd4853da9d1f597dfc2bb5ea",
  "agent-presentation-day-response-v1.schema.json": "1f01fc62452dc4e5748d16bd5e95936ea90a188177d0b9097d92d59c7c00a9e4",
  "agent-profile-response-v1.schema.json": "8b676bcee343c6cbc29e04c7a0cdbb19bdd780ee806ad82223a3ff12fd3e3a94",
  "agent-timeline-response-v1.schema.json": "1808c03d3a448d7fa4e62ddf207c85f3847eb7c7f33e0f828fa27452c4c02344",
  "api-error-v1.schema.json": "dd6e9b16cfe988e4d5a4ace0ae4b272d4d63df96204a20c2c37731148c769594",
  "boundary-pack-manifest-v1.schema.json": "c9939012d8bd3bb7d377ed9f708658a41a26af1e3eadfb3ac217fc43639023b5",
  "building-occupancy-v1.schema.json": "403be301ab728d7eca6091871a677dee30e9d2de66d3aaac823fe5c6ae8325e7",
  "building-render-pack-manifest-v1.schema.json": "ef78cdb25cd422a529690d08cbe7c4794454025c696eb5402e92a8e8cd50abf5",
  "clock-state-v1.schema.json": "1c9176cff0c4c036ceb64728a122b400e22f6b3594b18e9bb479e3b3711389ea",
  "completion-report-v1.schema.json": "6afe460ccc90b3a9503f5c4bf3a00b94b4c3f2be3606fe871e70cad20fee3943",
  "cube-response-v1.schema.json": "4328cdd9d8f7bdc032584a1b59782555a25dff1fda0c9db1896309c9d0f39b31",
  "environment-cycle-payload-v1.schema.json": "b8caf9ecd32c1d73043e1e92eb560828d352f61f6e7ffed84919eaceefe43a38",
  "environment-cycle-v1.schema.json": "7f8654cc7b1ac74d7b0629c4cd14cd9b4374e7a5936406c9072b1082c753df01",
  "environment-state-v1.schema.json": "58448a75b0a9b0c93cda52323366caf88286909834a4f83c7967bb8d8c2268e2",
  "event-datum-v1.schema.json": "18f7dd6117925b04f23ef7b3d9dc15e9771da1d4652ddb4f483658a8c542d992",
  "geography-catalog-v1.schema.json": "957dd0889a13692312003bf030c3f11e302ed4af6257ca812ddab87264fb220b",
  "geography-feature-v1.schema.json": "af181c2b94112f429d54aa3b34edddc6cf68f3c3689c400074a98f6e5a387491",
  "living-cell-manifest-v1.schema.json": "ce734669a288cabfe94a15ef0f42076e2180b8c12123ee755d184ee512345f07",
  "living-cell-slice-v1.schema.json": "ed3c442bc2ed18ea54f247adfcdeb793369004d205bfc355d95473d8347e36ec",
  "metric-catalog-v1.schema.json": "a9a7028d09b8e2744b331d315c13040736014bef5ec0f3ea1759d6d30cb55484",
  "metric-definition-v1.schema.json": "1a529fe11d90deec9c11837008720eb32a3cfcc6fabe7e2424e196a58858c79f",
  "mobility-presentation-bundle-v1.schema.json": "430727e9ec7f37a0550e44c1026e3587c8f647af40191a786ba686f46d768653",
  "movement-edge-v1.schema.json": "55f9fd39c3dc862ab6a04dc1e6cd2c6e14e08935c21b63a6d40ef5ab33e4c66e",
  "movement-graph-v1.schema.json": "ab9c252ddeb51af20295bf716345a74dd32a57e4c7eb7f15be0827adf75fb745",
  "movement-node-v1.schema.json": "1ebbaaabd40e006efc92e1a3274d2336c4745474dfdb1c13046c7370fea9a435",
  "person-presentation-projection-v1.schema.json": "d33e4589517ec7f0a279928c102b9b7546927184aa6ba2d439b15f2c305716c1",
  "population-datum-v1.schema.json": "8a8b00221370d15a9e847676e8c454d4fdb29c894f3e0e42d853318a11df5f9f",
  "renderer-performance-policy-v2.schema.json": "2aba7f42f3cdfdb5f27cab6139ec6515f57900dd8ddd8dbc80b564738ee57cff",
  "renderer-performance-policy-v3.schema.json": "6bfd6e2555b0f94930f035b2aef9dc162c094ac475ff7b223390e1026e07fa34",
  "renderer-quality-profile-v1.schema.json": "c46e6e98452014f96588ebe5d0435cff857f6235c797e7dae312048e31483beb",
  "run-catalog-v1.schema.json": "5fe59a3878896016f1fabee57c7b1fe8a26be120ce1abea083965d758912548c",
  "run-eligibility-catalog-v1.schema.json": "6ae99a208fd1482375b07a949f5548c340b866ccd6bf575c136e30e9926e5b07",
  "run-manifest-v1.schema.json": "f10c78834c3a1d8b1f5a4ddb9046f6360db77041c7e030f5094ce1dfe76810ed",
  "scenario-draft-v1.schema.json": "505a2c2cf51788da37aba5301a85f4d4fd640e45a256bec51c1c60de60d28d45",
  "scene-anchor-v1.schema.json": "90319326f3f958b59b1017e454df6c6a0f25e2d518e7af89d44d7b4341a1165b",
  "scene-catalog-response-v1.schema.json": "1c47fcaf9e3e458de7a2fa6cd31e59730e654e682122c5397b1e9d753501dc6e",
  "scene-cell-descriptor-v1.schema.json": "1c5d3d629fcfa0ee98aa67830c4a46390f78b2d1b916544ca506ff794538f784",
  "scene-cell-index-v1.schema.json": "9ef45e984a5bf758ba40c740a367d3fdec3f1fd7857359c80898d5c86dba3dc3",
  "scene-cell-payload-v1.schema.json": "6a7748ddfaa80d6a3350d18c3ed8bada0f4a0ecc251a9318390031bd65846546",
  "scene-completion-report-v1.schema.json": "d4bc5ee0ae4715ea48dba940c98e22f9378207be2e91e871167ec00b7836b070",
  "scene-layer-descriptor-v1.schema.json": "605ac9094cd6227e25a293af80a3247531b4e5a79e43e1062ad52b077793e598",
  "scene-manifest-v1.schema.json": "e2f43e4182b43b507039eeb01e1190ccb5a862d06009a58c1931845bef4e281f",
  "scene-source-snapshot-v1.schema.json": "b739a885608f95296ee9317bb47d29e24c5f20633a16151d03106caa9a451683",
  "scene-static-feature-v1.schema.json": "dfbe6e412149852935c7e3b38d2496057db7780e2690c01cc0a24d1cc105f09a",
  "scientific-datum-v1.schema.json": "983b85b149509dfe32a28b7cea24597eab39fb8221b36dfa03675479adfb17c2",
  "settlement-point-slice-v1.schema.json": "1b647fb6346044fbfc964352366c7d1ca467827cbe7e606b6bb5de9da5e711b4",
  "spatial-assignment-v1.schema.json": "13b1f2446227c5b3f7ac67cf7a68c16ff8a1217b82f6da17163e95ae008a0a29",
  "territory-metric-slice-v1.schema.json": "3bc5fcb343322bdf01dcbdf3995804de5efb5219d639e9611e9d32c227781761",
  "territory-node-v2.schema.json": "5c8e72f6b83959a42658e837704b3492a0e619f28e79c07061d4a1e27583c4fd",
  "territory-search-response-v1.schema.json": "8b23f20acb8e3362d8ea807948fa3986355d5dc8ee3e7589319857109beb5dd2",
  "territory-slice-v1.schema.json": "e71e4f2e414c0fcc485cbc8df549477c35510227bd4f8db65bb39871ecc2f63f",
  "vehicle-presentation-v1.schema.json": "3c486cdd41b4da11564a333986e1020439b69c5c905ecf07301fbd81556eb2a4",
  "visual-entity-v1.schema.json": "1cf4726ebfb46e9411fbfe7d4ddf164a132c9807ffe64e3e4126cf47608b77c7",
  "visual-entity-v2.schema.json": "915d095b8e4604fc13f29e897a67bc55c4138495f75306af8571dc2f37876af6",
  "world-viewport-response-v1.schema.json": "41fd0ce215614770bd5752cdab2d8374bf4155a0f5cf2a586dcfe3b89238dbb0",
  "world-viewport-response-v2.schema.json": "74f1cf701726f4d8f3b303239128a58e38612a7c5780332a52ad4f3798670640",
} as const;

/** Generated from agent-catalog-response-v1.schema.json. */
export type AgentCatalogResponseV1 = Readonly<{
  readonly classification: "local_restricted_focus_sample";
  readonly count: number;
  readonly items: ReadonlyArray<{
    readonly ageBand: string;
    readonly employmentStatus: string;
    readonly geographyId: string;
    readonly opaqueId: string;
    readonly sex: "female" | "male";
  }>;
  readonly privacy: {
    readonly identifier: "run_local_opaque";
    readonly rawPersonIdAvailable: false;
  };
  readonly runId: string;
  readonly runMetadata: {
    readonly dataCutoff: string;
    readonly geographyVintage: string;
    readonly runId: string;
    readonly runMode: "conditioned_reconstruction" | "free_run_backtest" | "forecast" | "scenario" | "synthetic";
    readonly scientificClaim: boolean;
  };
  readonly synthetic: boolean;
}>;

/** Generated from agent-mobility-presentation-v1.schema.json. */
export type AgentMobilityPresentationV1 = Readonly<{
  readonly activity: "home" | "work" | "study" | "travel" | "leisure";
  readonly assignment: {
    readonly assignmentId: string;
    readonly assignmentOrigin: "deterministic_scene_projection";
    readonly buildingId: string | null;
    readonly cellId: string;
    readonly classification: "visual_synthesis";
    readonly contractVersion: "1";
    readonly derivationVersion: "1.0.0";
    readonly edgeId: string | null;
    readonly opaqueId: string;
    readonly presenceKind: "building" | "pedestrian_route" | "vehicle";
    readonly presentationTime: string;
    readonly rawCoordinatesAvailable: false;
    readonly routeId: string | null;
    readonly runId: string;
    readonly sceneId: string;
    readonly scientificClaim: false;
    readonly vehicleId: string | null;
  };
  readonly contractVersion: "1";
  readonly derivationVersion: "1.0.0";
  readonly mobilityMode: "stationary" | "pedestrian" | "vehicle_passenger";
  readonly motion: {
    readonly direction: "forward" | "reverse" | null;
    readonly progress: number | null;
    readonly speedMps: number | null;
    readonly state: "stationary" | "moving" | "inherited_vehicle";
  };
  readonly opaqueId: string;
  readonly projectionScope: "focus_sample";
  readonly representation: "focus_person_1to1";
  readonly representedCount: 1;
  readonly runId: string;
  readonly scientificClaim: false;
  readonly vehicleId: string | null;
}>;

/** Generated from agent-presentation-day-response-v1.schema.json. */
export type AgentPresentationDayResponseV1 = Readonly<{
  readonly classification: "visual_synthesis";
  readonly modelTime: string;
  readonly opaqueId: string;
  readonly presentationDate: string;
  readonly schedule: ReadonlyArray<{
    readonly activity: "home" | "work" | "study" | "travel" | "leisure";
    readonly end: string;
    readonly placeKind: "home" | "route" | "work" | "study" | "leisure";
    readonly start: string;
  }>;
  readonly scientificClaim: false;
}>;

/** Generated from agent-profile-response-v1.schema.json. */
export type AgentProfileResponseV1 = Readonly<{
  readonly agent: {
    readonly ageBand: string;
    readonly employmentStatus: string;
    readonly geographyId: string;
    readonly householdSize: number;
    readonly opaqueId: string;
    readonly scientificState: {
      readonly geographyVintage: string;
      readonly provenance: "observed" | "derived" | "imputed" | "latent" | "simulated" | "prior" | "calibrated" | "synthetic";
      readonly stockAsOf: string;
    };
    readonly sex: "female" | "male";
  };
  readonly privacy: {
    readonly identifier: "run_local_opaque";
    readonly personalExportAllowed: false;
    readonly rawPersonIdAvailable: false;
    readonly scope: "local_only";
  };
}>;

/** Generated from agent-timeline-response-v1.schema.json. */
export type AgentTimelineResponseV1 = Readonly<{
  readonly opaqueId: string;
  readonly presentationEvents: ReadonlyArray<{
    readonly classification: "visual_synthesis";
    readonly kind: string;
    readonly time: string;
  }>;
  readonly scientificEvents: ReadonlyArray<unknown>;
  readonly scientificEventsStatus: "not_available_in_focus_projection";
}>;

/** Generated from api-error-v1.schema.json. */
export type ApiErrorV1 = Readonly<{
  readonly error: {
    readonly code: string;
    readonly message: string;
    readonly retryable: boolean;
  };
}>;

/** Generated from boundary-pack-manifest-v1.schema.json. */
export type BoundaryPackManifestV1 = Readonly<{
  readonly bbox: readonly [number, number, number, number];
  readonly contentEncoding: "gzip";
  readonly contentType: "application/geo+json";
  readonly coverage: {
    readonly checkpointPartial: boolean;
    readonly compiledMunicipalityFeatureCount: number;
    readonly compiledMunicipalitySubjectShardCount: number;
    readonly compiledSettlementPointCount: number;
    readonly compiledSettlementSliceCount: number;
    readonly countryCount: number;
    readonly expectedMunicipalityDimensionCount: number;
    readonly expectedMunicipalitySubjectShardCount: number;
    readonly federalDistrictCount: number;
    readonly presentationOnlySubjectCount: number;
    readonly provisionalMunicipalityFeatureCount: number;
    readonly subjectCount: number;
  };
  readonly datasetVersion: string;
  readonly format: "omnitwin.boundary-pack-manifest.v1";
  readonly generatedAt: string;
  readonly geographyVintage: string;
  readonly municipalityShards: ReadonlyArray<{
    readonly bbox: readonly [number, number, number, number];
    readonly bytes: number;
    readonly coverageStatus: "complete" | "partial" | "presentation_only_provisional" | "unavailable";
    readonly featureCount: number;
    readonly levels: ReadonlyArray<"municipality">;
    readonly path: string;
    readonly sha256: string;
    readonly subjectId: string;
    readonly url: string;
  }>;
  readonly national: {
    readonly bbox: readonly [number, number, number, number];
    readonly bytes: number;
    readonly featureCount: number;
    readonly levels: ReadonlyArray<"country" | "federal_district" | "subject">;
    readonly path: string;
    readonly sha256: string;
    readonly url: string;
  };
  readonly quality: {
    readonly antimeridianSplitFeatureCount: number;
    readonly coverageSimplificationFallbackGroupCount: number;
    readonly makeValidFeatureCount: number;
    readonly publicReleaseBlockers: ReadonlyArray<string>;
    readonly publicReleaseEligible: boolean;
  };
  readonly semantics: {
    readonly containsModelMetrics: false;
    readonly populationReference2021: "source_reference_not_model_metric";
    readonly runtimeNameJoinAllowed: false;
    readonly runtimeSpatialJoinAllowed: false;
  };
  readonly settlementSlices: ReadonlyArray<{
    readonly bbox: readonly [number, number, number, number];
    readonly bytes: number;
    readonly coverageStatus: "complete" | "partial" | "presentation_only_provisional" | "unavailable";
    readonly featureCount: number;
    readonly levels: ReadonlyArray<"settlement">;
    readonly municipalityId: string;
    readonly path: string;
    readonly sha256: string;
    readonly subjectId: string;
    readonly url: string;
  }>;
  readonly simplification: {
    readonly antimeridianPolicy: "unwrap_split_at_180_normalize_rfc7946";
    readonly coordinatePrecisionDecimals: number;
    readonly makeValid: true;
    readonly method: "shapely.coverage_simplify_or_topology_preserving_fallback";
    readonly municipalityToleranceDegrees: number;
    readonly subjectToleranceDegrees: number;
  };
  readonly sourceLedger: ReadonlyArray<{
    readonly bytes: number;
    readonly license: string;
    readonly pathHint: string;
    readonly rightsStatus: string;
    readonly role: string;
    readonly sha256: string;
    readonly sourceId: string;
  }>;
  readonly transport: "compressed_geojson_shards_v1";
  readonly version: number;
}>;

/** Generated from building-occupancy-v1.schema.json. */
export type BuildingOccupancyV1 = Readonly<{
  readonly buildingId: string;
  readonly capacityProxy: number | null;
  readonly cellId: string;
  readonly classification: "visual_synthesis";
  readonly contractVersion: "1";
  readonly membershipScope: "focus_sample_projection" | "containing_page" | "containing_cell";
  readonly occupantCount: number;
  readonly occupantOpaqueIds: ReadonlyArray<string>;
  readonly presentationTime: string;
  readonly projectionScope: "focus_sample";
  readonly runId: string;
  readonly sceneId: string;
  readonly scientificClaim: false;
}>;

/** Generated from building-render-pack-manifest-v1.schema.json. */
export type BuildingRenderPackManifestV1 = Readonly<{
  readonly attribution: {
    readonly license: string;
    readonly text: string;
    readonly url: string;
  };
  readonly bbox: readonly [number, number, number, number];
  readonly bytes: number;
  readonly contentType: "application/vnd.pmtiles";
  readonly contractVersion: "1";
  readonly datasetVersion: string;
  readonly fallbackCompatibility: {
    readonly normalizedSchema: "omnitwin.render_buildings.v1";
    readonly provider: "overture" | "openmaptiles";
    readonly tileMixingAllowed: false;
    readonly wholeSourceOnly: true;
  };
  readonly featureCounts: {
    readonly full: number;
    readonly merged: number;
    readonly simplified: number;
    readonly source: number;
  };
  readonly format: "omnitwin.building-render-pack.v1";
  readonly generatedAt: string;
  readonly immutable: true;
  readonly lodBands: readonly [{
    readonly maxZoom: number;
    readonly minZoom: number;
    readonly parentPartsMode: "parents_only" | "parts_preferred";
    readonly representation: "merged_footprints" | "simplified_footprints" | "full_geometry";
    readonly simplificationToleranceMeters: number;
    readonly sourceLayer: "building";
  }, {
    readonly maxZoom: number;
    readonly minZoom: number;
    readonly parentPartsMode: "parents_only" | "parts_preferred";
    readonly representation: "merged_footprints" | "simplified_footprints" | "full_geometry";
    readonly simplificationToleranceMeters: number;
    readonly sourceLayer: "building";
  }, {
    readonly maxZoom: number;
    readonly minZoom: number;
    readonly parentPartsMode: "parents_only" | "parts_preferred";
    readonly representation: "merged_footprints" | "simplified_footprints" | "full_geometry";
    readonly simplificationToleranceMeters: number;
    readonly sourceLayer: "building";
  }];
  readonly maxZoom: number;
  readonly minZoom: 13;
  readonly normalizedSchema: "omnitwin.render_buildings.v1";
  readonly packId: string;
  readonly provider: "overture" | "openmaptiles";
  readonly rights: {
    readonly browserCache: boolean;
    readonly edgeCache: boolean;
    readonly prefetch: "visible_only" | "visible_plus_one_ring";
    readonly proxy: boolean;
  };
  readonly sha256: string;
  readonly sourceLayers: ReadonlyArray<"building" | "building_part">;
  readonly subjectId: string;
  readonly transport: "pmtiles_http_range";
  readonly url: string;
}>;

/** Generated from clock-state-v1.schema.json. */
export type ClockStateV1 = Readonly<{
  readonly modelTime: string;
  readonly presentationTime: string;
  readonly speed: "paused" | "1x" | "4x" | "16x";
  readonly visualSynthesisSeed: number;
}>;

/** Generated from completion-report-v1.schema.json. */
export type CompletionReportV1 = Readonly<{
  readonly completedAt: string;
  readonly files: ReadonlyArray<{
    readonly bytes: number;
    readonly path: string;
    readonly rows: number | null;
    readonly sha256: string;
  }>;
  readonly format: "omnitwin.bundle.v1";
  readonly geographyVintage: string;
  readonly immutable: true;
  readonly runId: string;
  readonly status: "complete";
}>;

/** Generated from cube-response-v1.schema.json. */
export type CubeResponseV1 = Readonly<{
  readonly count: number;
  readonly cube: "population" | "events";
  readonly geographyVintage: string;
  readonly items: ReadonlyArray<{
    readonly ageBand: string;
    readonly coverage: number;
    readonly geographyId: string;
    readonly geographyVintage: string;
    readonly metric: "population";
    readonly periodEnd: null;
    readonly periodStart: null;
    readonly provenance: "observed" | "derived" | "imputed" | "latent" | "simulated" | "prior" | "calibrated" | "synthetic";
    readonly runMode: "conditioned_reconstruction" | "free_run_backtest" | "forecast" | "scenario" | "synthetic";
    readonly sex: "female" | "male";
    readonly stockAsOf: string;
    readonly uncertainty: {
      readonly lower: number | null;
      readonly upper: number | null;
    };
    readonly unit: "persons";
    readonly value: number | null;
  } | {
    readonly coverage: number;
    readonly eventType: string;
    readonly geographyId: string;
    readonly geographyVintage: string;
    readonly metric: string;
    readonly periodEnd: string;
    readonly periodStart: string;
    readonly provenance: "observed" | "derived" | "imputed" | "latent" | "simulated" | "prior" | "calibrated" | "synthetic";
    readonly runMode: "conditioned_reconstruction" | "free_run_backtest" | "forecast" | "scenario" | "synthetic";
    readonly stockAsOf: null;
    readonly uncertainty: {
      readonly lower: number | null;
      readonly upper: number | null;
    };
    readonly unit: "events";
    readonly value: number | null;
  }>;
  readonly runId: string;
}>;

/** Generated from environment-cycle-payload-v1.schema.json. */
export type EnvironmentCyclePayloadV1 = Readonly<{
  readonly cycleId: string;
  readonly sceneId: string;
  readonly steps: ReadonlyArray<{
    readonly cloudCover: number | null;
    readonly condition: "clear" | "cloudy" | "rain" | "snow" | "fog";
    readonly durationMinutes: number;
    readonly precipitationMmPerHour: number | null;
    readonly startMinute: number;
    readonly temperatureC: number | null;
    readonly windDirectionDegrees: number | null;
    readonly windMps: number | null;
  }>;
}>;

/** Generated from environment-cycle-v1.schema.json. */
export type EnvironmentCycleV1 = Readonly<{
  readonly content: {
    readonly bytes: number;
    readonly path: string;
    readonly recordCount: number;
    readonly sha256: string;
  };
  readonly cycleId: string;
  readonly fieldSources: {
    readonly condition: {
      readonly derivationVersion: string;
      readonly formula: string;
      readonly provenance: "visual_synthesis";
      readonly sourceId: string;
    };
    readonly meteorology: {
      readonly provenance: "reanalysis_environment" | "visual_synthesis";
      readonly sourceId: string;
    };
    readonly wind: {
      readonly derivationVersion: string | null;
      readonly formula: string | null;
      readonly provenance: "reanalysis_environment" | "visual_synthesis";
      readonly sourceId: string;
    };
  };
  readonly geographyId: string;
  readonly leapDayPolicy: "not_applicable" | "interpolate_feb_28_mar_1";
  readonly mode: "visual_preset" | "reanalysis_external";
  readonly period: "daily" | "annual_non_leap";
  readonly provenance: "reanalysis_environment" | "visual_synthesis";
  readonly referenceYear: 2025 | null;
  readonly sceneId: string;
  readonly scientificClaim: false;
  readonly sourceId: string;
  readonly sourceTimeZone: "UTC" | null;
  readonly timeZone: string;
  readonly timestepMinutes: number;
}>;

/** Generated from environment-state-v1.schema.json. */
export type EnvironmentStateV1 = Readonly<{
  readonly cloudCover: number | null;
  readonly condition: "clear" | "cloudy" | "rain" | "snow" | "fog";
  readonly environmentId: string;
  readonly fieldSources: {
    readonly condition: {
      readonly derivationVersion: string;
      readonly formula: string;
      readonly provenance: "visual_synthesis";
      readonly sourceId: string;
    };
    readonly meteorology: {
      readonly provenance: "reanalysis_environment" | "visual_synthesis";
      readonly sourceId: string;
    };
    readonly wind: {
      readonly derivationVersion: string | null;
      readonly formula: string | null;
      readonly provenance: "reanalysis_environment" | "visual_synthesis";
      readonly sourceId: string;
    };
  };
  readonly geographyId: string;
  readonly mode: "visual_preset" | "reanalysis_external";
  readonly precipitationMmPerHour: number | null;
  readonly provenance: "reanalysis_environment" | "visual_synthesis";
  readonly scientificClaim: false;
  readonly sourceId: string;
  readonly sourceReferences: ReadonlyArray<{
    readonly sourceTimeIso: string;
    readonly weight: number;
  }>;
  readonly sourceTime: string | null;
  readonly temperatureC: number | null;
  readonly validFrom: string;
  readonly validTo: string;
  readonly windDirectionDegrees: number | null;
  readonly windMps: number | null;
}>;

/** Generated from event-datum-v1.schema.json. */
export type EventDatumV1 = Readonly<{
  readonly coverage: number;
  readonly eventType: string;
  readonly geographyId: string;
  readonly geographyVintage: string;
  readonly metric: string;
  readonly periodEnd: string;
  readonly periodStart: string;
  readonly provenance: "observed" | "derived" | "imputed" | "latent" | "simulated" | "prior" | "calibrated" | "synthetic";
  readonly runMode: "conditioned_reconstruction" | "free_run_backtest" | "forecast" | "scenario" | "synthetic";
  readonly stockAsOf: null;
  readonly uncertainty: {
    readonly lower: number | null;
    readonly upper: number | null;
  };
  readonly unit: "events";
  readonly value: number | null;
}>;

/** Generated from geography-catalog-v1.schema.json. */
export type GeographyCatalogV1 = Readonly<{
  readonly count: number;
  readonly defaultFocusId: string;
  readonly geographyVintage: string;
  readonly items: ReadonlyArray<{
    readonly bbox: readonly [number, number, number, number];
    readonly centroid: readonly [number, number];
    readonly childCount: number;
    readonly childrenIds: ReadonlyArray<string>;
    readonly geographyVintage: string;
    readonly hasFocusPeople: boolean;
    readonly hasPopulation: boolean;
    readonly id: string;
    readonly level: "country" | "federal_district" | "subject" | "municipality" | "settlement" | "district";
    readonly nameEn: string;
    readonly nameRu: string;
    readonly parentId: string | null;
    readonly pathIds: ReadonlyArray<string>;
  }>;
  readonly rootIds: ReadonlyArray<string>;
  readonly runId: string;
  readonly selectionBasis: "focus_settlement_ancestor" | "population_settlement" | "population_hierarchy";
  readonly sliceRootId: string;
}>;

/** Generated from geography-feature-v1.schema.json. */
export type GeographyFeatureV1 = Readonly<{
  readonly bbox: readonly [number, number, number, number];
  readonly centroid: readonly [number, number];
  readonly geographyVintage: string;
  readonly id: string;
  readonly level: "country" | "federal_district" | "subject" | "municipality" | "settlement" | "district";
  readonly nameEn: string;
  readonly nameRu: string;
  readonly parentId: string | null;
}>;

/** Generated from living-cell-manifest-v1.schema.json. */
export type LivingCellManifestV1 = Readonly<{
  readonly bundleFingerprint: string;
  readonly cellZoom: 16;
  readonly classification: "local_restricted_focus_sample";
  readonly contractVersion: "1";
  readonly count: number;
  readonly format: "omnitwin.living-cells.v1";
  readonly geographyId: string;
  readonly geographyVintage: string;
  readonly immutable: true;
  readonly items: ReadonlyArray<{
    readonly agentCount: number;
    readonly buildingOccupancyCount: number;
    readonly bytes: number;
    readonly cellId: string;
    readonly path: string;
    readonly sha256: string;
    readonly url: string;
    readonly vehicleCount: number;
  }>;
  readonly modelStockAsOf: string;
  readonly presentationTime: string;
  readonly privacy: {
    readonly cachePolicy: "private_revalidate";
    readonly identifier: "run_local_opaque";
    readonly personalExportAllowed: false;
    readonly rawCoordinatesAvailable: false;
    readonly rawPersonIdAvailable: false;
    readonly scope: "local_only";
  };
  readonly projectionId: string;
  readonly projectionScope: "focus_sample";
  readonly projectionVersion: "1.0.0";
  readonly runId: string;
  readonly sceneId: string;
  readonly sceneManifestSha256: string;
  readonly scientificClaim: false;
  readonly sourceCompletedAt: string;
  readonly status: "complete";
  readonly totals: {
    readonly agents: number;
    readonly buildingOccupancies: number;
    readonly vehicles: number;
  };
}>;

/** Generated from living-cell-slice-v1.schema.json. */
export type LivingCellSliceV1 = Readonly<{
  readonly agents: ReadonlyArray<{
    readonly activity: "home" | "work" | "study" | "travel" | "leisure";
    readonly ageBand: string;
    readonly assignmentId: string;
    readonly buildingId: string | null;
    readonly cellId: string;
    readonly edgeId: string | null;
    readonly employmentStatus: string;
    readonly geographyId: string;
    readonly mobilityClassification: "visual_synthesis";
    readonly mobilityMode: "stationary" | "pedestrian" | "vehicle_passenger";
    readonly mobilityScientificClaim: false;
    readonly modelStockAsOf: string;
    readonly motion: {
      readonly direction: "forward" | "reverse" | null;
      readonly progress: number | null;
      readonly speedMps: number | null;
      readonly state: "stationary" | "moving" | "inherited_vehicle";
    };
    readonly opaqueId: string;
    readonly personProvenance: "observed" | "derived" | "imputed" | "latent" | "simulated" | "prior" | "calibrated" | "synthetic";
    readonly presenceKind: "building" | "pedestrian_route" | "vehicle";
    readonly representation: "focus_person_1to1";
    readonly representedCount: 1;
    readonly routeId: string | null;
    readonly sex: "female" | "male";
    readonly vehicleId: string | null;
  }>;
  readonly buildingOccupancies: ReadonlyArray<{
    readonly buildingId: string;
    readonly capacityProxy: number | null;
    readonly classification: "visual_synthesis";
    readonly membershipScope: "containing_cell";
    readonly occupantCount: number;
    readonly occupantOpaqueIds: ReadonlyArray<string>;
  }>;
  readonly bundleFingerprint: string;
  readonly cellId: string;
  readonly classification: "local_restricted_focus_sample";
  readonly contractVersion: "1";
  readonly counts: {
    readonly agents: number;
    readonly buildingOccupancies: number;
    readonly pedestrianAgents: number;
    readonly stationaryAgents: number;
    readonly vehiclePassengerAgents: number;
    readonly vehicles: number;
  };
  readonly geographyVintage: string;
  readonly modelStockAsOf: string;
  readonly presentationTime: string;
  readonly privacy: {
    readonly cachePolicy: "no-store";
    readonly identifier: "run_local_opaque";
    readonly personalExportAllowed: false;
    readonly rawCoordinatesAvailable: false;
    readonly rawPersonIdAvailable: false;
    readonly scope: "local_only";
  };
  readonly projectionId: string;
  readonly projectionScope: "focus_sample";
  readonly projectionVersion: "1.0.0";
  readonly runId: string;
  readonly sceneId: string;
  readonly sceneManifestSha256: string;
  readonly scientificClaim: false;
  readonly vehicles: ReadonlyArray<{
    readonly classification: "visual_synthesis";
    readonly direction: "forward" | "reverse";
    readonly edgeId: string;
    readonly membershipScope: "containing_cell";
    readonly passengerCount: number;
    readonly passengerOpaqueIds: ReadonlyArray<string>;
    readonly progress: number;
    readonly routeId: string;
    readonly speedMps: number;
    readonly vehicleId: string;
  }>;
}>;

/** Generated from metric-catalog-v1.schema.json. */
export type MetricCatalogV1 = Readonly<{
  readonly count: number;
  readonly defaultMetricId: "population.total";
  readonly geographyVintage: string;
  readonly items: ReadonlyArray<{
    readonly aggregation: "sum" | "ratio";
    readonly cube: "population" | "events";
    readonly id: string;
    readonly isDefault: boolean;
    readonly labelEn: string;
    readonly labelRu: string;
    readonly sourceMetric: string;
    readonly temporalKind: "stock" | "period";
    readonly unit: string;
    readonly valueKind: "count" | "rate" | "share" | "density";
  }>;
  readonly runId: string;
}>;

/** Generated from metric-definition-v1.schema.json. */
export type MetricDefinitionV1 = Readonly<{
  readonly aggregation: "sum" | "ratio";
  readonly cube: "population" | "events";
  readonly id: string;
  readonly isDefault: boolean;
  readonly labelEn: string;
  readonly labelRu: string;
  readonly sourceMetric: string;
  readonly temporalKind: "stock" | "period";
  readonly unit: string;
  readonly valueKind: "count" | "rate" | "share" | "density";
}>;

/** Generated from mobility-presentation-bundle-v1.schema.json. */
export type MobilityPresentationBundleV1 = Readonly<{
  readonly buildingOccupancies: ReadonlyArray<{
    readonly buildingId: string;
    readonly capacityProxy: number | null;
    readonly cellId: string;
    readonly classification: "visual_synthesis";
    readonly membershipScope: "containing_page";
    readonly occupantCount: number;
    readonly occupantOpaqueIds: ReadonlyArray<string>;
  }>;
  readonly bundleFingerprint: string;
  readonly classification: "local_restricted_focus_sample";
  readonly contractVersion: "1";
  readonly counts: {
    readonly buildingOccupancies: number;
    readonly focusPeopleTotal: number;
    readonly pageAgents: number;
    readonly pedestrianAgents: number;
    readonly stationaryAgents: number;
    readonly vehiclePassengerAgents: number;
    readonly vehicles: number;
  };
  readonly geographyId: string;
  readonly geographyVintage: string;
  readonly modelStockAsOf: string;
  readonly page: {
    readonly count: number;
    readonly limit: number;
    readonly nextOffset: number | null;
    readonly offset: number;
    readonly total: number;
  };
  readonly performancePolicy: {
    readonly continuousAnimationReasons: ReadonlyArray<"timeline_playback" | "active_weather_particles">;
    readonly continuousRepaint: false;
    readonly contractVersion: "2";
    readonly degradationOrder: readonly ["tree_billboards", "projected_shadows", "roof_caps", "facade_patterns"];
    readonly frameBudgetMs: number;
    readonly maxCanvasScale: 1;
    readonly peopleLimit: number;
    readonly policyId: "universal_lowpoly_presentation_v2";
    readonly reducedMotion: boolean;
    readonly schedulerMode: "invalidation_driven";
    readonly targetFps: number;
    readonly tier: "low" | "mid" | "high";
    readonly treeBillboardLimit: number;
    readonly vehicleLimit: number;
    readonly workerCount: 1;
  };
  readonly presentationTime: string;
  readonly privacy: {
    readonly cachePolicy: "no-store";
    readonly identifier: "run_local_opaque";
    readonly personalExportAllowed: false;
    readonly rawCoordinatesAvailable: false;
    readonly rawPersonIdAvailable: false;
    readonly scope: "local_only";
  };
  readonly projectionId: string;
  readonly projectionScope: "focus_sample";
  readonly projectionVersion: "1.0.0";
  readonly rosterItems: ReadonlyArray<{
    readonly activity: "home" | "work" | "study" | "travel" | "leisure";
    readonly ageBand: string;
    readonly assignmentId: string;
    readonly buildingId: string | null;
    readonly cellId: string;
    readonly edgeId: string | null;
    readonly employmentStatus: string;
    readonly geographyId: string;
    readonly mobilityClassification: "visual_synthesis";
    readonly mobilityMode: "stationary" | "pedestrian" | "vehicle_passenger";
    readonly mobilityScientificClaim: false;
    readonly modelStockAsOf: string;
    readonly opaqueId: string;
    readonly personProvenance: "observed" | "derived" | "imputed" | "latent" | "simulated" | "prior" | "calibrated" | "synthetic";
    readonly presenceKind: "building" | "pedestrian_route" | "vehicle";
    readonly routeId: string | null;
    readonly sex: "female" | "male";
    readonly vehicleId: string | null;
  }>;
  readonly runId: string;
  readonly sceneId: string;
  readonly sceneManifestSha256: string;
  readonly scientificClaim: false;
  readonly sourceStatus: "complete";
  readonly vehicles: ReadonlyArray<{
    readonly cellId: string;
    readonly classification: "visual_synthesis";
    readonly direction: "forward" | "reverse";
    readonly edgeId: string;
    readonly membershipScope: "containing_page";
    readonly passengerCount: number;
    readonly passengerOpaqueIds: ReadonlyArray<string>;
    readonly progress: number;
    readonly routeId: string;
    readonly speedMps: number;
    readonly vehicleId: string;
  }>;
}>;

/** Generated from movement-edge-v1.schema.json. */
export type MovementEdgeV1 = Readonly<{
  readonly allowedModes: ReadonlyArray<"pedestrian" | "bicycle" | "car" | "transit">;
  readonly cellIds: ReadonlyArray<string>;
  readonly crossesRoad: boolean;
  readonly direction: "bidirectional" | "forward" | "reverse";
  readonly edgeId: string;
  readonly edgeKind: "sidewalk" | "crosswalk" | "lane";
  readonly fieldSources: {
    readonly geometry: {
      readonly provenance: "external_cartography" | "derived_cartography";
      readonly sourceId: string;
    };
    readonly visualSpeed: {
      readonly derivationVersion: string;
      readonly provenance: "visual_synthesis";
      readonly sourceId: string;
    };
  };
  readonly fromNodeId: string;
  readonly geometryType: "line_string";
  readonly geometryWkbHex: string;
  readonly lengthMeters: number;
  readonly provenance: "external_cartography" | "derived_cartography";
  readonly roadClass: "motorway" | "trunk" | "primary" | "secondary" | "tertiary" | "residential" | "service" | "path" | "rail" | "other";
  readonly sceneId: string;
  readonly scientificClaim: false;
  readonly sourceId: string;
  readonly toNodeId: string;
  readonly visualSpeedMetersPerSecond: {
    readonly bicycle: number | null;
    readonly car: number | null;
    readonly pedestrian: number | null;
    readonly transit: number | null;
  };
}>;

/** Generated from movement-graph-v1.schema.json. */
export type MovementGraphV1 = Readonly<{
  readonly allowedModes: ReadonlyArray<"pedestrian" | "bicycle" | "car" | "transit">;
  readonly edgeCount: number;
  readonly edgeKinds: ReadonlyArray<"sidewalk" | "crosswalk" | "lane">;
  readonly edges: {
    readonly path: "network_edges.parquet";
    readonly sha256: string;
  };
  readonly fieldSources: {
    readonly geometry: {
      readonly provenance: "external_cartography" | "derived_cartography";
      readonly sourceIds: ReadonlyArray<string>;
    };
    readonly visualSpeed: {
      readonly derivationVersion: string;
      readonly provenance: "visual_synthesis";
      readonly sourceIds: ReadonlyArray<string>;
    };
  };
  readonly graphVersion: string;
  readonly nodeCount: number;
  readonly nodes: {
    readonly path: "network_nodes.parquet";
    readonly sha256: string;
  };
  readonly provenance: "external_cartography" | "derived_cartography";
  readonly routeCount: number;
  readonly routeIdPolicy: "authored_stable_scene_route_v1";
  readonly routePartitioning: "cell_payload_route_complete_v1";
  readonly sceneId: string;
  readonly scientificClaim: false;
  readonly sourceIds: ReadonlyArray<string>;
}>;

/** Generated from movement-node-v1.schema.json. */
export type MovementNodeV1 = Readonly<{
  readonly cellId: string;
  readonly nodeId: string;
  readonly position: readonly [number, number];
  readonly provenance: "external_cartography" | "derived_cartography";
  readonly sceneId: string;
  readonly scientificClaim: false;
  readonly sourceId: string;
}>;

/** Generated from person-presentation-projection-v1.schema.json. */
export type PersonPresentationProjectionV1 = Readonly<{
  readonly ageBand: string;
  readonly classification: "local_restricted_focus_sample";
  readonly contractVersion: "1";
  readonly employmentStatus: string;
  readonly geographyId: string;
  readonly geographyVintage: string;
  readonly householdSize: number;
  readonly opaqueId: string;
  readonly privacy: {
    readonly identifier: "run_local_opaque";
    readonly personalExportAllowed: false;
    readonly rawCoordinatesAvailable: false;
    readonly rawPersonIdAvailable: false;
    readonly scope: "local_only";
  };
  readonly projectionScope: "focus_sample";
  readonly provenance: "observed" | "derived" | "imputed" | "latent" | "simulated" | "prior" | "calibrated" | "synthetic";
  readonly runId: string;
  readonly sex: "female" | "male";
  readonly stockAsOf: string;
}>;

/** Generated from population-datum-v1.schema.json. */
export type PopulationDatumV1 = Readonly<{
  readonly ageBand: string;
  readonly coverage: number;
  readonly geographyId: string;
  readonly geographyVintage: string;
  readonly metric: "population";
  readonly periodEnd: null;
  readonly periodStart: null;
  readonly provenance: "observed" | "derived" | "imputed" | "latent" | "simulated" | "prior" | "calibrated" | "synthetic";
  readonly runMode: "conditioned_reconstruction" | "free_run_backtest" | "forecast" | "scenario" | "synthetic";
  readonly sex: "female" | "male";
  readonly stockAsOf: string;
  readonly uncertainty: {
    readonly lower: number | null;
    readonly upper: number | null;
  };
  readonly unit: "persons";
  readonly value: number | null;
}>;

/** Generated from renderer-performance-policy-v2.schema.json. */
export type RendererPerformancePolicyV2 = Readonly<{
  readonly continuousAnimationReasons: ReadonlyArray<"timeline_playback" | "active_weather_particles">;
  readonly continuousRepaint: false;
  readonly contractVersion: "2";
  readonly degradationOrder: readonly ["tree_billboards", "projected_shadows", "roof_caps", "facade_patterns"];
  readonly frameBudgetMs: number;
  readonly maxCanvasScale: 1;
  readonly peopleLimit: number;
  readonly policyId: "universal_lowpoly_presentation_v2";
  readonly reducedMotion: boolean;
  readonly schedulerMode: "invalidation_driven";
  readonly targetFps: number;
  readonly tier: "low" | "mid" | "high";
  readonly treeBillboardLimit: number;
  readonly vehicleLimit: number;
  readonly workerCount: 1;
}>;

/** Generated from renderer-performance-policy-v3.schema.json. */
export type RendererPerformancePolicyV3 = Readonly<{
  readonly contractVersion: "3";
  readonly degradationOrder: readonly ["motion_profile", "dpr", "individual_actors", "contact_ao", "aggregate_buildings", "compatibility_30"];
  readonly dprLadder: ReadonlyArray<number>;
  readonly lod: {
    readonly guardRingCells: 1;
    readonly individualActorsMinZoom: 15.5;
    readonly livingCellZoom: 16;
    readonly moving: {
      readonly basemapMaxOverscale: number;
      readonly basemapTileLodBias: number;
      readonly buildingsMaxOverscale: number;
      readonly buildingsTileLodBias: number;
    };
    readonly settled: {
      readonly basemapMaxOverscale: number;
      readonly basemapTileLodBias: number;
      readonly buildingsMaxOverscale: number;
      readonly buildingsTileLodBias: number;
    };
  };
  readonly minimumMovingFps: 30;
  readonly movingFrameBudgetMs: 33.333;
  readonly phaseProfiles: {
    readonly camera_motion: {
      readonly actorMode: "aggregate" | "individual" | "budgeted";
      readonly buildingMode: "aggregate_2_5d" | "single_extrusion" | "full_budgeted";
      readonly contactAo: boolean;
      readonly facadePattern: boolean;
      readonly projectedShadow: boolean;
      readonly roofCap: boolean;
      readonly treeBillboards: boolean;
    };
    readonly compatibility_30: {
      readonly actorMode: "aggregate" | "individual" | "budgeted";
      readonly buildingMode: "aggregate_2_5d" | "single_extrusion" | "full_budgeted";
      readonly contactAo: boolean;
      readonly facadePattern: boolean;
      readonly projectedShadow: boolean;
      readonly roofCap: boolean;
      readonly treeBillboards: boolean;
    };
    readonly emergency_30: {
      readonly actorMode: "aggregate" | "individual" | "budgeted";
      readonly buildingMode: "aggregate_2_5d" | "single_extrusion" | "full_budgeted";
      readonly contactAo: boolean;
      readonly facadePattern: boolean;
      readonly projectedShadow: boolean;
      readonly roofCap: boolean;
      readonly treeBillboards: boolean;
    };
    readonly general_plan: {
      readonly actorMode: "aggregate" | "individual" | "budgeted";
      readonly buildingMode: "aggregate_2_5d" | "single_extrusion" | "full_budgeted";
      readonly contactAo: boolean;
      readonly facadePattern: boolean;
      readonly projectedShadow: boolean;
      readonly roofCap: boolean;
      readonly treeBillboards: boolean;
    };
    readonly living_motion: {
      readonly actorMode: "aggregate" | "individual" | "budgeted";
      readonly buildingMode: "aggregate_2_5d" | "single_extrusion" | "full_budgeted";
      readonly contactAo: boolean;
      readonly facadePattern: boolean;
      readonly projectedShadow: boolean;
      readonly roofCap: boolean;
      readonly treeBillboards: boolean;
    };
    readonly settled_paused: {
      readonly actorMode: "aggregate" | "individual" | "budgeted";
      readonly buildingMode: "aggregate_2_5d" | "single_extrusion" | "full_budgeted";
      readonly contactAo: boolean;
      readonly facadePattern: boolean;
      readonly projectedShadow: boolean;
      readonly roofCap: boolean;
      readonly treeBillboards: boolean;
    };
  };
  readonly pitchMaxDegrees: 60;
  readonly policyId: "universal_lowpoly_motion_floor_v3";
  readonly reducedMotion: boolean;
  readonly scheduler: {
    readonly continuousRepaint: false;
    readonly deckAnimate: false;
    readonly maxFps: number;
    readonly mode: "invalidation_driven_capped";
    readonly pausedMode: "event_driven";
  };
  readonly targetFps: number;
  readonly targetFrameBudgetMs: number;
  readonly tier: "low" | "mid" | "high";
  readonly watchdog: {
    readonly compatibilityAfterMs: 1500;
    readonly emergencyAfterMs: 500;
    readonly gpuMinimumSamples: 30;
    readonly gpuSampleDeadlineMs: 1000;
    readonly minimumStepIntervalMs: 5000;
    readonly overBudgetFrameMs: 33.333;
    readonly recoveryAfterMs: 10000;
  };
  readonly workerCount: 1;
}>;

/** Generated from renderer-quality-profile-v1.schema.json. */
export type RendererQualityProfileV1 = Readonly<{
  readonly atmosphere: boolean;
  readonly lodTransitionMs: number;
  readonly maxPixelRatio: number;
  readonly pedestrianLimit: number;
  readonly profileId: "low" | "balanced" | "high" | "custom";
  readonly reducedMotion: boolean;
  readonly shadowQuality: "off" | "low" | "high";
  readonly vehicleLimit: number;
  readonly workerCount: number;
}>;

/** Generated from run-catalog-v1.schema.json. */
export type RunCatalogV1 = Readonly<{
  readonly activeRunId: string | null;
  readonly count: number;
  readonly items: ReadonlyArray<{
    readonly completedAt: string;
    readonly dataCutoff: string;
    readonly geographyVintage: string;
    readonly runId: string;
    readonly runMode: "conditioned_reconstruction" | "free_run_backtest" | "forecast" | "scenario" | "synthetic";
    readonly scientificClaim: boolean;
    readonly status: "complete";
  }>;
}>;

/** Generated from run-eligibility-catalog-v1.schema.json. */
export type RunEligibilityCatalogV1 = Readonly<{
  readonly activeRunId: string | null;
  readonly count: number;
  readonly items: ReadonlyArray<{
    readonly activation: "eligible" | "inspection_only";
    readonly attestationSha256: string | null;
    readonly bundleFingerprint: string;
    readonly detail: string | null;
    readonly evaluatedAt: string | null;
    readonly qaStatus: "pass" | "fail" | "not_evaluated" | "stale";
    readonly runId: string;
  }>;
}>;

/** Generated from run-manifest-v1.schema.json. */
export type RunManifestV1 = Readonly<{
  readonly completedAt: string;
  readonly dataCutoff: string;
  readonly forecastOrigin: string | null;
  readonly format: "omnitwin.bundle.v1";
  readonly geographyVintage: string;
  readonly hashes: Readonly<Record<string, string>>;
  readonly predictiveValidation: boolean;
  readonly provenance: {
    readonly classification: "synthetic" | "observed" | "derived" | "imputed" | "simulated";
    readonly notes: string;
    readonly source: string;
  };
  readonly runId: string;
  readonly runMode: "conditioned_reconstruction" | "free_run_backtest" | "forecast" | "scenario" | "synthetic";
  readonly scenarioId: string | null;
  readonly scientificClaim: boolean;
  readonly seed: number;
  readonly stableReleaseEligible: boolean;
  readonly status: "complete";
  readonly version: string;
}>;

/** Generated from scenario-draft-v1.schema.json. */
export type ScenarioDraftV1 = Readonly<{
  readonly baselineRunId: string;
  readonly createdAt: string;
  readonly description: string;
  readonly geographyId: string;
  readonly id: string;
  readonly parameters: Readonly<Record<string, number | string | boolean | null>>;
  readonly revision: number;
  readonly status: "draft";
  readonly title: string;
  readonly updatedAt: string;
}>;

/** Generated from scene-anchor-v1.schema.json. */
export type SceneAnchorV1 = Readonly<{
  readonly anchorId: string;
  readonly capacityProxy: number | null;
  readonly category: "home" | "work" | "study" | "leisure" | "transit";
  readonly cellId: string;
  readonly geographyId: string;
  readonly position: readonly [number, number];
  readonly positionOrigin: "public_cartography" | "cell_centroid" | "deterministic_cell_synthesis";
  readonly provenance: "external_cartography" | "derived_cartography" | "visual_synthesis";
  readonly sceneId: string;
  readonly scientificClaim: false;
  readonly sourceId: string;
}>;

/** Generated from scene-catalog-response-v1.schema.json. */
export type SceneCatalogResponseV1 = Readonly<{
  readonly binding: {
    readonly reasonCodes: ReadonlyArray<"scene_not_found" | "geography_vintage_mismatch" | "geography_spatial_mismatch" | "coverage_miss" | "multiple_compatible_scenes" | "scene_not_selected" | "layer_unavailable" | "offline_fallback">;
    readonly selectedSceneId: string | null;
    readonly status: "compatible" | "not_found" | "ambiguous" | "incompatible";
  };
  readonly count: number;
  readonly geographyId: string;
  readonly geographyVintage: string;
  readonly items: ReadonlyArray<{
    readonly capabilities: {
      readonly anchors: boolean;
      readonly environmentPresets: boolean;
      readonly externalEnvironment: false;
      readonly movementNetwork: boolean;
      readonly reanalysisEnvironment: boolean;
      readonly staticFeatures: boolean;
      readonly z16Cells: boolean;
    };
    readonly cellIndexSha256: string;
    readonly cellIndexUrl: string;
    readonly compatibility: "compatible" | "incompatible";
    readonly compatibilityReasons: ReadonlyArray<"geography_vintage_mismatch" | "geography_spatial_mismatch" | "coverage_miss" | "layer_unavailable">;
    readonly coverage: {
      readonly bbox: readonly [number, number, number, number];
      readonly geographyCatalogSha256: string;
      readonly geographyIds: ReadonlyArray<string>;
      readonly longitudeWrap: "none" | "antimeridian";
      readonly zMax: number;
      readonly zMin: number;
    };
    readonly geographyVintage: string;
    readonly layers: ReadonlyArray<{
      readonly classification: "external_cartography" | "reanalysis_environment" | "derived_cartography" | "visual_synthesis";
      readonly layerId: "cells" | "features" | "network_nodes" | "network_edges" | "anchors" | "environment";
      readonly path: "cells.parquet" | "features.parquet" | "network_nodes.parquet" | "network_edges.parquet" | "anchors.parquet" | "environment.parquet";
      readonly reason: string | null;
      readonly sha256: string;
      readonly sourceIds: ReadonlyArray<string>;
      readonly status: "available" | "unavailable" | "offline_fallback";
    }>;
    readonly manifestSha256: string;
    readonly manifestUrl: string;
    readonly sceneId: string;
    readonly sceneVersion: string;
    readonly sources: ReadonlyArray<{
      readonly adapter: string;
      readonly cartographyMetadata: {
        readonly licenseId: string;
        readonly osmSnapshotId: string | null;
        readonly overtureRelease: string | null;
        readonly overtureTheme: string | null;
        readonly provider: "overture" | "openstreetmap";
        readonly upstreamSources: ReadonlyArray<{
          readonly attribution: string;
          readonly license: string;
          readonly name: string;
        }>;
      } | null;
      readonly environmentMetadata: {
        readonly datasetId: string;
        readonly doi: string | null;
        readonly grid: {
          readonly crs: string;
          readonly resolutionDegrees: number;
        };
        readonly retrievedAt: string;
        readonly revision: string;
        readonly temporalCoverage: {
          readonly end: string;
          readonly start: string;
          readonly year: 2025;
        };
        readonly temporalResolution: "PT1H";
        readonly variableUnits: Readonly<Record<string, string>>;
        readonly variables: ReadonlyArray<string>;
      } | null;
      readonly inputSha256: string;
      readonly license: {
        readonly attribution: string;
        readonly name: string;
        readonly url: string | null;
      };
      readonly provenance: "external_cartography" | "reanalysis_environment" | "derived_cartography" | "visual_synthesis";
      readonly snapshotAt: string;
      readonly sourceId: string;
      readonly sourceType: "cartography" | "landcover" | "transport_network" | "points_of_interest" | "environment" | "visual_synthesis";
    }>;
    readonly timeZone: string;
  }>;
  readonly runId: string;
  readonly timeZone: string | null;
}>;

/** Generated from scene-cell-descriptor-v1.schema.json. */
export type SceneCellDescriptorV1 = Readonly<{
  readonly allocationShares: {
    readonly jobs: number;
    readonly leisure: number;
    readonly population: number;
    readonly study: number;
  };
  readonly bbox: readonly [number, number, number, number];
  readonly cellId: string;
  readonly centroid: readonly [number, number];
  readonly content: {
    readonly format: "pmtiles" | "flatgeobuf" | "binary";
    readonly path: string;
    readonly sha256: string;
  } | null;
  readonly fieldSources: {
    readonly allocation: {
      readonly derivationVersion: string | null;
      readonly provenance: "derived_cartography" | "visual_synthesis";
      readonly sourceId: string;
    };
    readonly geometry: {
      readonly provenance: "external_cartography" | "derived_cartography";
      readonly sourceId: string;
    };
    readonly landUse: {
      readonly derivationVersion: string | null;
      readonly provenance: "external_cartography" | "derived_cartography" | "visual_synthesis";
      readonly sourceId: string;
    };
  };
  readonly geographyId: string;
  readonly landUseClass: "residential" | "mixed_use" | "commercial" | "industrial" | "education" | "leisure" | "transport" | "green" | "water" | "other";
  readonly provenance: "external_cartography" | "derived_cartography" | "visual_synthesis";
  readonly sceneId: string;
  readonly scientificClaim: false;
  readonly sourceIds: ReadonlyArray<string>;
  readonly x: number;
  readonly y: number;
  readonly z: 16;
}>;

/** Generated from scene-cell-index-v1.schema.json. */
export type SceneCellIndexV1 = Readonly<{
  readonly count: number;
  readonly derivationVersion: string;
  readonly items: ReadonlyArray<{
    readonly bytes: number;
    readonly cellId: string;
    readonly path: string;
    readonly sha256: string;
    readonly url: string;
  }>;
  readonly sceneId: string;
}>;

/** Generated from scene-cell-payload-v1.schema.json. */
export type SceneCellPayloadV1 = Readonly<{
  readonly anchors: ReadonlyArray<{
    readonly anchorId: string;
    readonly capacityProxy: number | null;
    readonly category: "home" | "work" | "study" | "leisure" | "transit";
    readonly cellId: string;
    readonly geographyId: string;
    readonly position: readonly [number, number];
    readonly positionOrigin: "public_cartography" | "cell_centroid" | "deterministic_cell_synthesis";
    readonly provenance: "external_cartography" | "derived_cartography" | "visual_synthesis";
    readonly sceneId: string;
    readonly scientificClaim: false;
    readonly sourceId: string;
  }>;
  readonly cellId: string;
  readonly contentAssets: ReadonlyArray<{
    readonly bytes: number;
    readonly path: string;
    readonly sha256: string;
    readonly url: string;
  }>;
  readonly derivationVersion: string;
  readonly descriptor: {
    readonly allocationShares: {
      readonly jobs: number;
      readonly leisure: number;
      readonly population: number;
      readonly study: number;
    };
    readonly bbox: readonly [number, number, number, number];
    readonly cellId: string;
    readonly centroid: readonly [number, number];
    readonly content: {
      readonly format: "pmtiles" | "flatgeobuf" | "binary";
      readonly path: string;
      readonly sha256: string;
    } | null;
    readonly fieldSources: {
      readonly allocation: {
        readonly derivationVersion: string | null;
        readonly provenance: "derived_cartography" | "visual_synthesis";
        readonly sourceId: string;
      };
      readonly geometry: {
        readonly provenance: "external_cartography" | "derived_cartography";
        readonly sourceId: string;
      };
      readonly landUse: {
        readonly derivationVersion: string | null;
        readonly provenance: "external_cartography" | "derived_cartography" | "visual_synthesis";
        readonly sourceId: string;
      };
    };
    readonly geographyId: string;
    readonly landUseClass: "residential" | "mixed_use" | "commercial" | "industrial" | "education" | "leisure" | "transport" | "green" | "water" | "other";
    readonly provenance: "external_cartography" | "derived_cartography" | "visual_synthesis";
    readonly sceneId: string;
    readonly scientificClaim: false;
    readonly sourceIds: ReadonlyArray<string>;
    readonly x: number;
    readonly y: number;
    readonly z: 16;
  };
  readonly edges: ReadonlyArray<{
    readonly allowedModes: ReadonlyArray<"pedestrian" | "bicycle" | "car" | "transit">;
    readonly cellIds: ReadonlyArray<string>;
    readonly crossesRoad: boolean;
    readonly direction: "bidirectional" | "forward" | "reverse";
    readonly edgeId: string;
    readonly edgeKind: "sidewalk" | "crosswalk" | "lane";
    readonly fieldSources: {
      readonly geometry: {
        readonly provenance: "external_cartography" | "derived_cartography";
        readonly sourceId: string;
      };
      readonly visualSpeed: {
        readonly derivationVersion: string;
        readonly provenance: "visual_synthesis";
        readonly sourceId: string;
      };
    };
    readonly fromNodeId: string;
    readonly geometryType: "line_string";
    readonly geometryWkbHex: string;
    readonly lengthMeters: number;
    readonly provenance: "external_cartography" | "derived_cartography";
    readonly roadClass: "motorway" | "trunk" | "primary" | "secondary" | "tertiary" | "residential" | "service" | "path" | "rail" | "other";
    readonly sceneId: string;
    readonly scientificClaim: false;
    readonly sourceId: string;
    readonly toNodeId: string;
    readonly visualSpeedMetersPerSecond: {
      readonly bicycle: number | null;
      readonly car: number | null;
      readonly pedestrian: number | null;
      readonly transit: number | null;
    };
  }>;
  readonly features: ReadonlyArray<{
    readonly capacityProxy: number | null;
    readonly category: string | null;
    readonly cellIds: ReadonlyArray<string>;
    readonly displayName: string | null;
    readonly featureId: string;
    readonly featureKind: "building" | "road" | "landcover" | "water" | "park" | "poi" | "transit_stop";
    readonly fieldSources: {
      readonly attributes: {
        readonly derivationVersion: string | null;
        readonly provenance: "external_cartography" | "derived_cartography" | "visual_synthesis" | "not_available";
        readonly sourceId: string | null;
      };
      readonly capacity: {
        readonly derivationVersion: string | null;
        readonly provenance: "external_cartography" | "derived_cartography" | "visual_synthesis" | "not_available";
        readonly sourceId: string | null;
      };
      readonly geometry: {
        readonly provenance: "external_cartography" | "derived_cartography";
        readonly sourceId: string;
      };
    };
    readonly geographyId: string | null;
    readonly geometryType: "point" | "line_string" | "polygon";
    readonly geometryWkbHex: string;
    readonly heightMeters: number | null;
    readonly levels: number | null;
    readonly provenance: "external_cartography" | "derived_cartography" | "visual_synthesis";
    readonly sceneId: string;
    readonly scientificClaim: false;
    readonly sourceId: string;
  }>;
  readonly nodes: ReadonlyArray<{
    readonly cellId: string;
    readonly nodeId: string;
    readonly position: readonly [number, number];
    readonly provenance: "external_cartography" | "derived_cartography";
    readonly sceneId: string;
    readonly scientificClaim: false;
    readonly sourceId: string;
  }>;
  readonly routes: ReadonlyArray<{
    readonly edgeIds: ReadonlyArray<string>;
    readonly fieldSources: {
      readonly derivationVersion: string;
      readonly provenance: "visual_synthesis";
      readonly sourceIds: ReadonlyArray<string>;
    };
    readonly mode: "pedestrian" | "bicycle" | "car" | "transit";
    readonly routeId: string;
    readonly traversal: "loop" | "ping_pong" | "once";
  }>;
  readonly sceneId: string;
}>;

/** Generated from scene-completion-report-v1.schema.json. */
export type SceneCompletionReportV1 = Readonly<{
  readonly completedAt: string;
  readonly files: ReadonlyArray<{
    readonly bytes: number;
    readonly path: "scene.json" | "cells.parquet" | "features.parquet" | "network_nodes.parquet" | "network_edges.parquet" | "anchors.parquet" | "environment.parquet" | string;
    readonly rows: number | null;
    readonly sha256: string;
  }>;
  readonly format: "omnitwin.scene.v1";
  readonly geographyVintage: string;
  readonly immutable: true;
  readonly sceneId: string;
  readonly status: "complete";
}>;

/** Generated from scene-layer-descriptor-v1.schema.json. */
export type SceneLayerDescriptorV1 = Readonly<{
  readonly bytes: number;
  readonly classification: "external_cartography" | "reanalysis_environment" | "derived_cartography" | "visual_synthesis";
  readonly format: "parquet";
  readonly layerId: "cells" | "features" | "network_nodes" | "network_edges" | "anchors" | "environment";
  readonly maxZoom: number | null;
  readonly minZoom: number | null;
  readonly path: "cells.parquet" | "features.parquet" | "network_nodes.parquet" | "network_edges.parquet" | "anchors.parquet" | "environment.parquet";
  readonly required: boolean;
  readonly rows: number;
  readonly sha256: string;
  readonly sourceIds: ReadonlyArray<string>;
}>;

/** Generated from scene-manifest-v1.schema.json. */
export type SceneManifestV1 = Readonly<{
  readonly basemap: null | {
    readonly attribution: string;
    readonly bytes: number;
    readonly format: "pmtiles";
    readonly path: string;
    readonly sha256: string;
    readonly sourceIds: ReadonlyArray<string>;
  };
  readonly capabilities: {
    readonly anchors: boolean;
    readonly environmentPresets: boolean;
    readonly externalEnvironment: false;
    readonly movementNetwork: boolean;
    readonly reanalysisEnvironment: boolean;
    readonly staticFeatures: boolean;
    readonly z16Cells: boolean;
  };
  readonly cellIndex: {
    readonly bytes: number;
    readonly cellCount: number;
    readonly path: "content/cells/index.json";
    readonly sha256: string;
  };
  readonly completedAt: string;
  readonly contentHashes: Readonly<Record<string, string>>;
  readonly coverage: {
    readonly bbox: readonly [number, number, number, number];
    readonly geographyCatalogSha256: string;
    readonly geographyIds: ReadonlyArray<string>;
    readonly longitudeWrap: "none" | "antimeridian";
    readonly zMax: number;
    readonly zMin: number;
  };
  readonly environmentCycles: ReadonlyArray<{
    readonly content: {
      readonly bytes: number;
      readonly path: string;
      readonly recordCount: number;
      readonly sha256: string;
    };
    readonly cycleId: string;
    readonly fieldSources: {
      readonly condition: {
        readonly derivationVersion: string;
        readonly formula: string;
        readonly provenance: "visual_synthesis";
        readonly sourceId: string;
      };
      readonly meteorology: {
        readonly provenance: "reanalysis_environment" | "visual_synthesis";
        readonly sourceId: string;
      };
      readonly wind: {
        readonly derivationVersion: string | null;
        readonly formula: string | null;
        readonly provenance: "reanalysis_environment" | "visual_synthesis";
        readonly sourceId: string;
      };
    };
    readonly geographyId: string;
    readonly leapDayPolicy: "not_applicable" | "interpolate_feb_28_mar_1";
    readonly mode: "visual_preset" | "reanalysis_external";
    readonly period: "daily" | "annual_non_leap";
    readonly provenance: "reanalysis_environment" | "visual_synthesis";
    readonly referenceYear: 2025 | null;
    readonly sceneId: string;
    readonly scientificClaim: false;
    readonly sourceId: string;
    readonly sourceTimeZone: "UTC" | null;
    readonly timeZone: string;
    readonly timestepMinutes: number;
  }>;
  readonly format: "omnitwin.scene.v1";
  readonly geographyVintage: string;
  readonly hashes: {
    readonly "anchors.parquet": string;
    readonly "cells.parquet": string;
    readonly "environment.parquet": string;
    readonly "features.parquet": string;
    readonly "network_edges.parquet": string;
    readonly "network_nodes.parquet": string;
  };
  readonly immutable: true;
  readonly layers: ReadonlyArray<{
    readonly bytes: number;
    readonly classification: "external_cartography" | "reanalysis_environment" | "derived_cartography" | "visual_synthesis";
    readonly format: "parquet";
    readonly layerId: "cells" | "features" | "network_nodes" | "network_edges" | "anchors" | "environment";
    readonly maxZoom: number | null;
    readonly minZoom: number | null;
    readonly path: "cells.parquet" | "features.parquet" | "network_nodes.parquet" | "network_edges.parquet" | "anchors.parquet" | "environment.parquet";
    readonly required: boolean;
    readonly rows: number;
    readonly sha256: string;
    readonly sourceIds: ReadonlyArray<string>;
  }>;
  readonly movementGraph: {
    readonly allowedModes: ReadonlyArray<"pedestrian" | "bicycle" | "car" | "transit">;
    readonly edgeCount: number;
    readonly edgeKinds: ReadonlyArray<"sidewalk" | "crosswalk" | "lane">;
    readonly edges: {
      readonly path: "network_edges.parquet";
      readonly sha256: string;
    };
    readonly fieldSources: {
      readonly geometry: {
        readonly provenance: "external_cartography" | "derived_cartography";
        readonly sourceIds: ReadonlyArray<string>;
      };
      readonly visualSpeed: {
        readonly derivationVersion: string;
        readonly provenance: "visual_synthesis";
        readonly sourceIds: ReadonlyArray<string>;
      };
    };
    readonly graphVersion: string;
    readonly nodeCount: number;
    readonly nodes: {
      readonly path: "network_nodes.parquet";
      readonly sha256: string;
    };
    readonly provenance: "external_cartography" | "derived_cartography";
    readonly routeCount: number;
    readonly routeIdPolicy: "authored_stable_scene_route_v1";
    readonly routePartitioning: "cell_payload_route_complete_v1";
    readonly sceneId: string;
    readonly scientificClaim: false;
    readonly sourceIds: ReadonlyArray<string>;
  };
  readonly sceneId: string;
  readonly sceneVersion: string;
  readonly scientificClaim: false;
  readonly sourceSnapshots: ReadonlyArray<{
    readonly adapter: string;
    readonly cartographyMetadata: {
      readonly licenseId: string;
      readonly osmSnapshotId: string | null;
      readonly overtureRelease: string | null;
      readonly overtureTheme: string | null;
      readonly provider: "overture" | "openstreetmap";
      readonly upstreamSources: ReadonlyArray<{
        readonly attribution: string;
        readonly license: string;
        readonly name: string;
      }>;
    } | null;
    readonly coverage: {
      readonly bbox: readonly [number, number, number, number];
      readonly geographyIds: ReadonlyArray<string>;
      readonly longitudeWrap: "none" | "antimeridian";
    };
    readonly environmentMetadata: {
      readonly datasetId: string;
      readonly doi: string | null;
      readonly grid: {
        readonly crs: string;
        readonly resolutionDegrees: number;
      };
      readonly retrievedAt: string;
      readonly revision: string;
      readonly temporalCoverage: {
        readonly end: string;
        readonly start: string;
        readonly year: number;
      };
      readonly temporalResolution: "PT1H";
      readonly variableUnits: Readonly<Record<string, string>>;
      readonly variables: ReadonlyArray<string>;
    } | null;
    readonly inputPath: string;
    readonly inputSha256: string;
    readonly license: {
      readonly attribution: string;
      readonly name: string;
      readonly url: string | null;
    };
    readonly provenance: "external_cartography" | "reanalysis_environment" | "derived_cartography" | "visual_synthesis";
    readonly scientificClaim: false;
    readonly snapshotAt: string;
    readonly sourceId: string;
    readonly sourceType: "cartography" | "landcover" | "transport_network" | "points_of_interest" | "environment" | "visual_synthesis";
  }>;
  readonly status: "complete";
  readonly timeZone: string;
}>;

/** Generated from scene-source-snapshot-v1.schema.json. */
export type SceneSourceSnapshotV1 = Readonly<{
  readonly adapter: string;
  readonly cartographyMetadata: {
    readonly licenseId: string;
    readonly osmSnapshotId: string | null;
    readonly overtureRelease: string | null;
    readonly overtureTheme: string | null;
    readonly provider: "overture" | "openstreetmap";
    readonly upstreamSources: ReadonlyArray<{
      readonly attribution: string;
      readonly license: string;
      readonly name: string;
    }>;
  } | null;
  readonly coverage: {
    readonly bbox: readonly [number, number, number, number];
    readonly geographyIds: ReadonlyArray<string>;
    readonly longitudeWrap: "none" | "antimeridian";
  };
  readonly environmentMetadata: {
    readonly datasetId: string;
    readonly doi: string | null;
    readonly grid: {
      readonly crs: string;
      readonly resolutionDegrees: number;
    };
    readonly retrievedAt: string;
    readonly revision: string;
    readonly temporalCoverage: {
      readonly end: string;
      readonly start: string;
      readonly year: number;
    };
    readonly temporalResolution: "PT1H";
    readonly variableUnits: Readonly<Record<string, string>>;
    readonly variables: ReadonlyArray<string>;
  } | null;
  readonly inputPath: string;
  readonly inputSha256: string;
  readonly license: {
    readonly attribution: string;
    readonly name: string;
    readonly url: string | null;
  };
  readonly provenance: "external_cartography" | "reanalysis_environment" | "derived_cartography" | "visual_synthesis";
  readonly scientificClaim: false;
  readonly snapshotAt: string;
  readonly sourceId: string;
  readonly sourceType: "cartography" | "landcover" | "transport_network" | "points_of_interest" | "environment" | "visual_synthesis";
}>;

/** Generated from scene-static-feature-v1.schema.json. */
export type SceneStaticFeatureV1 = Readonly<{
  readonly capacityProxy: number | null;
  readonly category: string | null;
  readonly cellIds: ReadonlyArray<string>;
  readonly displayName: string | null;
  readonly featureId: string;
  readonly featureKind: "building" | "road" | "landcover" | "water" | "park" | "poi" | "transit_stop";
  readonly fieldSources: {
    readonly attributes: {
      readonly derivationVersion: string | null;
      readonly provenance: "external_cartography" | "derived_cartography" | "visual_synthesis" | "not_available";
      readonly sourceId: string | null;
    };
    readonly capacity: {
      readonly derivationVersion: string | null;
      readonly provenance: "external_cartography" | "derived_cartography" | "visual_synthesis" | "not_available";
      readonly sourceId: string | null;
    };
    readonly geometry: {
      readonly provenance: "external_cartography" | "derived_cartography";
      readonly sourceId: string;
    };
  };
  readonly geographyId: string | null;
  readonly geometryType: "point" | "line_string" | "polygon";
  readonly geometryWkbHex: string;
  readonly heightMeters: number | null;
  readonly levels: number | null;
  readonly provenance: "external_cartography" | "derived_cartography" | "visual_synthesis";
  readonly sceneId: string;
  readonly scientificClaim: false;
  readonly sourceId: string;
}>;

/** Generated from scientific-datum-v1.schema.json. */
export type ScientificDatumV1 = Readonly<{
  readonly coverage: number;
  readonly geographyId: string;
  readonly geographyVintage: string;
  readonly metric: string;
  readonly periodEnd: string | null;
  readonly periodStart: string | null;
  readonly provenance: "observed" | "derived" | "imputed" | "latent" | "simulated" | "prior" | "calibrated" | "synthetic";
  readonly stockAsOf: string | null;
  readonly uncertainty: {
    readonly lower: number | null;
    readonly upper: number | null;
  };
  readonly unit: string;
  readonly value: number | null;
}>;

/** Generated from settlement-point-slice-v1.schema.json. */
export type SettlementPointSliceV1 = Readonly<{
  readonly count: number;
  readonly geographyVintage: string;
  readonly items: ReadonlyArray<{
    readonly canEnter3d: boolean;
    readonly centroid: readonly [number, number];
    readonly coverageStatus: "complete" | "partial" | "presentation_only_provisional" | "unavailable";
    readonly id: string;
    readonly modelGeographyId: string | null;
    readonly nameEn: string;
    readonly nameRu: string;
    readonly population: number | null;
    readonly populationCoverage: number | null;
    readonly populationProvenance: ReadonlyArray<"observed" | "derived" | "imputed" | "latent" | "simulated" | "prior" | "calibrated" | "synthetic">;
    readonly populationSource: "model_bundle";
    readonly populationStatus: "available" | "missing" | "not_linked";
    readonly populationStockAsOf: string | null;
    readonly representation: "source_point" | "presentation_only_provisional" | "model_bundle_fallback";
    readonly scientificClaim: boolean;
    readonly settlementType: string | null;
  }>;
  readonly municipalityId: string;
  readonly runId: string;
  readonly source: "national_boundary_pack" | "model_bundle_fallback";
}>;

/** Generated from spatial-assignment-v1.schema.json. */
export type SpatialAssignmentV1 = Readonly<{
  readonly assignmentId: string;
  readonly assignmentOrigin: "deterministic_scene_projection";
  readonly buildingId: string | null;
  readonly cellId: string;
  readonly classification: "visual_synthesis";
  readonly contractVersion: "1";
  readonly derivationVersion: "1.0.0";
  readonly edgeId: string | null;
  readonly opaqueId: string;
  readonly presenceKind: "building" | "pedestrian_route" | "vehicle";
  readonly presentationTime: string;
  readonly rawCoordinatesAvailable: false;
  readonly routeId: string | null;
  readonly runId: string;
  readonly sceneId: string;
  readonly scientificClaim: false;
  readonly vehicleId: string | null;
}>;

/** Generated from territory-metric-slice-v1.schema.json. */
export type TerritoryMetricSliceV1 = Readonly<{
  readonly complete: boolean;
  readonly count: number;
  readonly geographyVintage: string;
  readonly items: ReadonlyArray<{
    readonly coverage: number | null;
    readonly modelGeographyId: string | null;
    readonly periodEnd: string | null;
    readonly periodStart: string | null;
    readonly provenance: ReadonlyArray<"observed" | "derived" | "imputed" | "latent" | "simulated" | "prior" | "calibrated" | "synthetic">;
    readonly status: "available" | "missing" | "not_linked";
    readonly stockAsOf: string | null;
    readonly territoryId: string;
    readonly unit: string;
    readonly value: number | null;
  }>;
  readonly metric: {
    readonly aggregation: "sum" | "ratio";
    readonly cube: "population" | "events";
    readonly id: string;
    readonly isDefault: boolean;
    readonly labelEn: string;
    readonly labelRu: string;
    readonly sourceMetric: string;
    readonly temporalKind: "stock" | "period";
    readonly unit: string;
    readonly valueKind: "count" | "rate" | "share" | "density";
  };
  readonly runId: string;
  readonly source: "model_bundle";
  readonly territoryId: string;
}>;

/** Generated from territory-node-v2.schema.json. */
export type TerritoryNodeV2 = Readonly<{
  readonly bbox: readonly [number, number, number, number];
  readonly canEnter3d: boolean;
  readonly centroid: readonly [number, number];
  readonly childCount: number;
  readonly coverageStatus: "complete" | "partial" | "presentation_only_provisional" | "unavailable";
  readonly geographyVintage: string;
  readonly hasModelData: boolean;
  readonly id: string;
  readonly level: "country" | "federal_district" | "subject" | "municipality" | "settlement" | "district";
  readonly modelGeographyId: string | null;
  readonly nameEn: string;
  readonly nameRu: string;
  readonly parentId: string | null;
  readonly pathIds: ReadonlyArray<string>;
  readonly representation: "source_boundary" | "source_point" | "presentation_only_provisional" | "model_bundle_fallback";
}>;

/** Generated from territory-search-response-v1.schema.json. */
export type TerritorySearchResponseV1 = Readonly<{
  readonly count: number;
  readonly geographyVintage: string;
  readonly items: ReadonlyArray<{
    readonly bbox: readonly [number, number, number, number];
    readonly canEnter3d: boolean;
    readonly centroid: readonly [number, number];
    readonly childCount: number;
    readonly coverageStatus: "complete" | "partial" | "presentation_only_provisional" | "unavailable";
    readonly geographyVintage: string;
    readonly hasModelData: boolean;
    readonly id: string;
    readonly level: "country" | "federal_district" | "subject" | "municipality" | "settlement" | "district";
    readonly modelGeographyId: string | null;
    readonly nameEn: string;
    readonly nameRu: string;
    readonly parentId: string | null;
    readonly pathIds: ReadonlyArray<string>;
    readonly representation: "source_boundary" | "source_point" | "presentation_only_provisional" | "model_bundle_fallback";
  }>;
  readonly query: string;
  readonly runId: string;
  readonly scopeParentId: string | null;
  readonly truncated: boolean;
}>;

/** Generated from territory-slice-v1.schema.json. */
export type TerritorySliceV1 = Readonly<{
  readonly count: number;
  readonly geographyVintage: string;
  readonly items: ReadonlyArray<{
    readonly bbox: readonly [number, number, number, number];
    readonly canEnter3d: boolean;
    readonly centroid: readonly [number, number];
    readonly childCount: number;
    readonly coverageStatus: "complete" | "partial" | "presentation_only_provisional" | "unavailable";
    readonly geographyVintage: string;
    readonly hasModelData: boolean;
    readonly id: string;
    readonly level: "country" | "federal_district" | "subject" | "municipality" | "settlement" | "district";
    readonly modelGeographyId: string | null;
    readonly nameEn: string;
    readonly nameRu: string;
    readonly parentId: string | null;
    readonly pathIds: ReadonlyArray<string>;
    readonly representation: "source_boundary" | "source_point" | "presentation_only_provisional" | "model_bundle_fallback";
  }>;
  readonly parent: {
    readonly bbox: readonly [number, number, number, number];
    readonly canEnter3d: boolean;
    readonly centroid: readonly [number, number];
    readonly childCount: number;
    readonly coverageStatus: "complete" | "partial" | "presentation_only_provisional" | "unavailable";
    readonly geographyVintage: string;
    readonly hasModelData: boolean;
    readonly id: string;
    readonly level: "country" | "federal_district" | "subject" | "municipality" | "settlement" | "district";
    readonly modelGeographyId: string | null;
    readonly nameEn: string;
    readonly nameRu: string;
    readonly parentId: string | null;
    readonly pathIds: ReadonlyArray<string>;
    readonly representation: "source_boundary" | "source_point" | "presentation_only_provisional" | "model_bundle_fallback";
  };
  readonly runId: string;
  readonly source: "national_boundary_pack" | "model_bundle_fallback";
}>;

/** Generated from vehicle-presentation-v1.schema.json. */
export type VehiclePresentationV1 = Readonly<{
  readonly cellId: string;
  readonly classification: "visual_synthesis";
  readonly contractVersion: "1";
  readonly direction: "forward" | "reverse";
  readonly edgeId: string;
  readonly membershipScope: "focus_sample_projection" | "containing_page" | "containing_cell";
  readonly passengerCount: number;
  readonly passengerIdentity: "run_local_opaque_focus_people";
  readonly passengerOpaqueIds: ReadonlyArray<string>;
  readonly presentationTime: string;
  readonly progress: number;
  readonly projectionScope: "focus_sample";
  readonly rawCoordinatesAvailable: false;
  readonly representedPopulation: 0;
  readonly routeId: string;
  readonly runId: string;
  readonly sceneId: string;
  readonly scientificClaim: false;
  readonly speedMps: number;
  readonly vehicleClass: "car";
  readonly vehicleId: string;
}>;

/** Generated from visual-entity-v1.schema.json. */
export type VisualEntityV1 = Readonly<{
  readonly activity: "home" | "work" | "study" | "travel" | "leisure" | "ambient";
  readonly heading: number;
  readonly id: string;
  readonly latitude: number;
  readonly longitude: number;
  readonly modelTime: string;
  readonly positionOrigin: "privacy_grid_centroid" | "deterministic_viewport_synthesis";
  readonly presentationCellId: string | null;
  readonly presentationTime: string;
  readonly rawSourceCoordinateUsed: false;
  readonly representation: "focus_person_1to1" | "aggregate_proxy" | "ambient_only";
  readonly representedCount: number;
  readonly sourceGeographyId: string;
  readonly spatialResolutionM: number | null;
}>;

/** Generated from visual-entity-v2.schema.json. */
export type VisualEntityV2 = Readonly<{
  readonly activity: "home" | "work" | "study" | "travel" | "leisure" | "ambient";
  readonly activityScheduleProfile: number | null;
  readonly entityKind: "person" | "vehicle" | "bicycle" | "transit_vehicle";
  readonly heading: number;
  readonly id: string;
  readonly motion: {
    readonly direction: "forward" | "reverse" | null;
    readonly edgeId: string | null;
    readonly mode: "stationary" | "network_edge" | "cell_interpolation";
    readonly progress: number | null;
    readonly routeId: string | null;
    readonly speedMps: number;
  };
  readonly position: {
    readonly cellId: string;
    readonly geometrySemantics: "privacy_grid_centroid" | "deterministic_cell_point" | "authored_network_point";
    readonly latitude: number;
    readonly longitude: number;
    readonly origin: "public_scene_anchor" | "scene_cell_centroid" | "privacy_grid_centroid" | "deterministic_cell_synthesis" | "network_interpolation";
    readonly rawSourceCoordinateUsed: false;
    readonly sceneId: string;
    readonly semantics: "synthetic_presentation_cell";
    readonly spatialResolutionM: number | null;
  };
  readonly presentationTime: string;
  readonly representation: "focus_person_1to1" | "aggregate_proxy" | "ambient_only";
  readonly representedCount: number;
  readonly scientificClaim: false;
  readonly sourceGeographyId: string;
  readonly visualSynthesisVersion: string;
}>;

/** Generated from world-viewport-response-v1.schema.json. */
export type WorldViewportResponseV1 = Readonly<{
  readonly ambientEntities: number;
  readonly classification: "visual_synthesis";
  readonly entities: ReadonlyArray<{
    readonly activity: "home" | "work" | "study" | "travel" | "leisure" | "ambient";
    readonly heading: number;
    readonly id: string;
    readonly latitude: number;
    readonly longitude: number;
    readonly modelTime: string;
    readonly positionOrigin: "privacy_grid_centroid" | "deterministic_viewport_synthesis";
    readonly presentationCellId: string | null;
    readonly presentationTime: string;
    readonly rawSourceCoordinateUsed: false;
    readonly representation: "focus_person_1to1" | "aggregate_proxy" | "ambient_only";
    readonly representedCount: number;
    readonly sourceGeographyId: string;
    readonly spatialResolutionM: number | null;
  }>;
  readonly geographyId: string;
  readonly geographyVintage: string;
  readonly modelTime: string;
  readonly renderedPopulationEntities: number;
  readonly representedPopulation: number;
  readonly runId: string;
  readonly scientificClaim: false;
  readonly seed: number;
}>;

/** Generated from world-viewport-response-v2.schema.json. */
export type WorldViewportResponseV2 = Readonly<{
  readonly clocks: {
    readonly modelTime: string;
    readonly presentationTime: string;
    readonly speed: "paused" | "1x" | "4x" | "16x";
    readonly visualSynthesisSeed: number;
  };
  readonly contractVersion: "2";
  readonly environment: {
    readonly classification: "visual_synthesis" | "reanalysis_environment";
    readonly cloudCover: number | null;
    readonly condition: "clear" | "cloudy" | "rain" | "snow" | "fog";
    readonly environmentId: string;
    readonly fieldSources: {
      readonly condition: {
        readonly derivationVersion: string;
        readonly formula: string;
        readonly provenance: "visual_synthesis";
        readonly sourceId: string;
      };
      readonly meteorology: {
        readonly provenance: "reanalysis_environment" | "visual_synthesis";
        readonly sourceId: string;
      };
      readonly wind: {
        readonly derivationVersion: string | null;
        readonly formula: string | null;
        readonly provenance: "reanalysis_environment" | "visual_synthesis";
        readonly sourceId: string;
      };
    };
    readonly geographyId: string;
    readonly mode: "visual_preset" | "reanalysis_external";
    readonly precipitationMmPerHour: number | null;
    readonly scientificClaim: false;
    readonly sourceId: string;
    readonly sourceReferences: ReadonlyArray<{
      readonly sourceTimeIso: string;
      readonly weight: number;
    }>;
    readonly sourceTime: string | null;
    readonly temperatureC: number | null;
    readonly temporalMapping: {
      readonly classification: "visual_synthesis";
      readonly derivationVersion: "1.0.0" | null;
      readonly formula: "scalars=weighted_mean;precipitation_null=0;condition=max(weight,severity[snow>rain>fog>cloudy>clear],-step_index);wind_from=atan2(sum(weight*speed*sin(from)),sum(weight*speed*cos(from)));wind_speed=hypot(sum(weight*speed*sin(from)),sum(weight*speed*cos(from)))" | null;
      readonly leapDayPolicy: "not_applicable" | "interpolate_feb_28_mar_1";
      readonly policy: "identity" | "daily_cycle" | "annual_2025_non_leap_replay";
      readonly presentationTime: string;
      readonly referenceYear: 2025 | null;
    };
    readonly validFrom: string;
    readonly validTo: string;
    readonly windDirectionDegrees: number | null;
    readonly windMps: number | null;
  };
  readonly geographyId: string;
  readonly geographyVintage: string;
  readonly modelState: {
    readonly classification: "model_state";
    readonly coverage: number;
    readonly populationStock: number | null;
    readonly provenance: ReadonlyArray<"observed" | "derived" | "imputed" | "latent" | "simulated" | "prior" | "calibrated" | "synthetic">;
    readonly runMode: "conditioned_reconstruction" | "free_run_backtest" | "forecast" | "scenario" | "synthetic";
    readonly scientificClaim: boolean;
    readonly status: "available" | "not_available";
    readonly stockAsOf: string | null;
    readonly uncertainty: {
      readonly lower: number | null;
      readonly upper: number | null;
    };
  };
  readonly runActivation: "eligible" | "inspection_only";
  readonly runId: string;
  readonly sceneId: string;
  readonly sourceLayerStatus: ReadonlyArray<{
    readonly classification: "model_state" | "external_cartography" | "reanalysis_environment" | "derived_cartography" | "visual_synthesis";
    readonly layerId: "model_state" | "cells" | "features" | "network_nodes" | "network_edges" | "anchors" | "environment";
    readonly reason: string | null;
    readonly sourceIds: ReadonlyArray<string>;
    readonly status: "available" | "unavailable" | "offline_fallback";
  }>;
  readonly visualSynthesis: {
    readonly activityScheduling: {
      readonly classification: "visual_synthesis";
      readonly derivationVersion: "1.0.0";
      readonly formula: "network_edge=>activity=travel,profile=null;otherwise profile=stable_seed(run_id,scene_id,entity_id,'activity-schedule')%12;activity=hourly_profile[profile][scene_local_hour]";
      readonly policy: "scene_local_hourly_profile_v1";
      readonly scientificClaim: false;
      readonly timeZone: string;
    };
    readonly ambientEntities: number;
    readonly classification: "visual_synthesis";
    readonly coordinateSemantics: "webmercator_privacy_grid_min_250m";
    readonly entities: ReadonlyArray<{
      readonly activity: "home" | "work" | "study" | "travel" | "leisure" | "ambient";
      readonly activityScheduleProfile: number | null;
      readonly entityKind: "person" | "vehicle" | "bicycle" | "transit_vehicle";
      readonly heading: number;
      readonly id: string;
      readonly motion: {
        readonly direction: "forward" | "reverse" | null;
        readonly edgeId: string | null;
        readonly mode: "stationary" | "network_edge" | "cell_interpolation";
        readonly progress: number | null;
        readonly routeId: string | null;
        readonly speedMps: number;
      };
      readonly position: {
        readonly cellId: string;
        readonly geometrySemantics: "privacy_grid_centroid" | "deterministic_cell_point" | "authored_network_point";
        readonly latitude: number;
        readonly longitude: number;
        readonly origin: "public_scene_anchor" | "scene_cell_centroid" | "privacy_grid_centroid" | "deterministic_cell_synthesis" | "network_interpolation";
        readonly rawSourceCoordinateUsed: false;
        readonly sceneId: string;
        readonly semantics: "synthetic_presentation_cell";
        readonly spatialResolutionM: number | null;
      };
      readonly presentationTime: string;
      readonly representation: "focus_person_1to1" | "aggregate_proxy" | "ambient_only";
      readonly representedCount: number;
      readonly scientificClaim: false;
      readonly sourceGeographyId: string;
      readonly visualSynthesisVersion: string;
    }>;
    readonly rawAddressCoordinatesAvailable: false;
    readonly renderedPopulationEntities: number;
    readonly rendererQuality: {
      readonly atmosphere: boolean;
      readonly lodTransitionMs: number;
      readonly maxPixelRatio: number;
      readonly pedestrianLimit: number;
      readonly profileId: "low" | "balanced" | "high" | "custom";
      readonly reducedMotion: boolean;
      readonly shadowQuality: "off" | "low" | "high";
      readonly vehicleLimit: number;
      readonly workerCount: number;
    };
    readonly representationCoverage: number;
    readonly representedPopulation: number;
    readonly scientificClaim: false;
    readonly seed: number;
    readonly unrepresentedPopulation: number;
    readonly version: string;
    readonly viewportAllocatedPopulation: number;
  };
}>;
